//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aran.Delta.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aran.Delta.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimuth to the nearest point on the line : .
        /// </summary>
        internal static string azimuthTwoNearestPoint {
            get {
                return ResourceManager.GetString("azimuthTwoNearestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimuth from &quot;Point 1&quot; to &quot;Point 2&quot; :.
        /// </summary>
        internal static string azimuthTwoPoints {
            get {
                return ResourceManager.GetString("azimuthTwoPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chkByClick {
            get {
                object obj = ResourceManager.GetObject("chkByClick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from point to line :.
        /// </summary>
        internal static string distanceToLine {
            get {
                return ResourceManager.GetString("distanceToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance between two points.
        /// </summary>
        internal static string distanceTwoPoints {
            get {
                return ResourceManager.GetString("distanceTwoPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignatedPoint :.
        /// </summary>
        internal static string dPoint {
            get {
                return ResourceManager.GetString("dPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max : .
        /// </summary>
        internal static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min : .
        /// </summary>
        internal static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navaid :.
        /// </summary>
        internal static string navaid {
            get {
                return ResourceManager.GetString("navaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point :.
        /// </summary>
        internal static string point {
            get {
                return ResourceManager.GetString("point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string str111 {
            get {
                return ResourceManager.GetString("str111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string str112 {
            get {
                return ResourceManager.GetString("str112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        internal static string str125 {
            get {
                return ResourceManager.GetString("str125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knot.
        /// </summary>
        internal static string str126 {
            get {
                return ResourceManager.GetString("str126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string str519 {
            get {
                return ResourceManager.GetString("str519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NM.
        /// </summary>
        internal static string str520 {
            get {
                return ResourceManager.GetString("str520", resourceCulture);
            }
        }
    }
}
