'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Aran.PANDA.SRVectoring.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to km.
        '''</summary>
        Friend ReadOnly Property str0100() As String
            Get
                Return ResourceManager.GetString("str0100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NM.
        '''</summary>
        Friend ReadOnly Property str0101() As String
            Get
                Return ResourceManager.GetString("str0101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to m.
        '''</summary>
        Friend ReadOnly Property str0102() As String
            Get
                Return ResourceManager.GetString("str0102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ft.
        '''</summary>
        Friend ReadOnly Property str0103() As String
            Get
                Return ResourceManager.GetString("str0103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to kM/h.
        '''</summary>
        Friend ReadOnly Property str0104() As String
            Get
                Return ResourceManager.GetString("str0104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kt.
        '''</summary>
        Friend ReadOnly Property str0105() As String
            Get
                Return ResourceManager.GetString("str0105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to m/min.
        '''</summary>
        Friend ReadOnly Property str0106() As String
            Get
                Return ResourceManager.GetString("str0106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to feet/min.
        '''</summary>
        Friend ReadOnly Property str0107() As String
            Get
                Return ResourceManager.GetString("str0107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -.
        '''</summary>
        Friend ReadOnly Property str0198() As String
            Get
                Return ResourceManager.GetString("str0198", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -.
        '''</summary>
        Friend ReadOnly Property str0199() As String
            Get
                Return ResourceManager.GetString("str0199", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True bearing.
        '''</summary>
        Friend ReadOnly Property str0200() As String
            Get
                Return ResourceManager.GetString("str0200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distance.
        '''</summary>
        Friend ReadOnly Property str0202() As String
            Get
                Return ResourceManager.GetString("str0202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Radial.
        '''</summary>
        Friend ReadOnly Property str0203() As String
            Get
                Return ResourceManager.GetString("str0203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peleng.
        '''</summary>
        Friend ReadOnly Property str0204() As String
            Get
                Return ResourceManager.GetString("str0204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True bearing:.
        '''</summary>
        Friend ReadOnly Property str0205() As String
            Get
                Return ResourceManager.GetString("str0205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Magn. bearing:.
        '''</summary>
        Friend ReadOnly Property str0206() As String
            Get
                Return ResourceManager.GetString("str0206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Altitude.
        '''</summary>
        Friend ReadOnly Property str0207() As String
            Get
                Return ResourceManager.GetString("str0207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Height.
        '''</summary>
        Friend ReadOnly Property str0208() As String
            Get
                Return ResourceManager.GetString("str0208", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latitude.
        '''</summary>
        Friend ReadOnly Property str0209() As String
            Get
                Return ResourceManager.GetString("str0209", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Longitude.
        '''</summary>
        Friend ReadOnly Property str0210() As String
            Get
                Return ResourceManager.GetString("str0210", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Friend ReadOnly Property str0211() As String
            Get
                Return ResourceManager.GetString("str0211", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -.
        '''</summary>
        Friend ReadOnly Property str0299() As String
            Get
                Return ResourceManager.GetString("str0299", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  of circle center.
        '''</summary>
        Friend ReadOnly Property str0300() As String
            Get
                Return ResourceManager.GetString("str0300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interval of allowable value:.
        '''</summary>
        Friend ReadOnly Property str0301() As String
            Get
                Return ResourceManager.GetString("str0301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  from .
        '''</summary>
        Friend ReadOnly Property str0302() As String
            Get
                Return ResourceManager.GetString("str0302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  till .
        '''</summary>
        Friend ReadOnly Property str0303() As String
            Get
                Return ResourceManager.GetString("str0303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to With the given radius it is impossible to leave on the given point..
        '''</summary>
        Friend ReadOnly Property str0304() As String
            Get
                Return ResourceManager.GetString("str0304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn radius.
        '''</summary>
        Friend ReadOnly Property str0305() As String
            Get
                Return ResourceManager.GetString("str0305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn direction.
        '''</summary>
        Friend ReadOnly Property str0306() As String
            Get
                Return ResourceManager.GetString("str0306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Course change.
        '''</summary>
        Friend ReadOnly Property str0307() As String
            Get
                Return ResourceManager.GetString("str0307", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right.
        '''</summary>
        Friend ReadOnly Property str0308() As String
            Get
                Return ResourceManager.GetString("str0308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left.
        '''</summary>
        Friend ReadOnly Property str0309() As String
            Get
                Return ResourceManager.GetString("str0309", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn arc length.
        '''</summary>
        Friend ReadOnly Property str0310() As String
            Get
                Return ResourceManager.GetString("str0310", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -.
        '''</summary>
        Friend ReadOnly Property str0399() As String
            Get
                Return ResourceManager.GetString("str0399", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is no solution..
        '''</summary>
        Friend ReadOnly Property str0500() As String
            Get
                Return ResourceManager.GetString("str0500", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distance to the next point.
        '''</summary>
        Friend ReadOnly Property str0501() As String
            Get
                Return ResourceManager.GetString("str0501", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save files....
        '''</summary>
        Friend ReadOnly Property str0502() As String
            Get
                Return ResourceManager.GetString("str0502", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculation report.
        '''</summary>
        Friend ReadOnly Property str0503() As String
            Get
                Return ResourceManager.GetString("str0503", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Radar vectoring - Calculation report.
        '''</summary>
        Friend ReadOnly Property str0504() As String
            Get
                Return ResourceManager.GetString("str0504", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Radar vectoring.
        '''</summary>
        Friend ReadOnly Property str1000() As String
            Get
                Return ResourceManager.GetString("str1000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial parameters.
        '''</summary>
        Friend ReadOnly Property str1001() As String
            Get
                Return ResourceManager.GetString("str1001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manoeuvres.
        '''</summary>
        Friend ReadOnly Property str1002() As String
            Get
                Return ResourceManager.GetString("str1002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Straight course.
        '''</summary>
        Friend ReadOnly Property str1003() As String
            Get
                Return ResourceManager.GetString("str1003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn.
        '''</summary>
        Friend ReadOnly Property str1004() As String
            Get
                Return ResourceManager.GetString("str1004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intercept course.
        '''</summary>
        Friend ReadOnly Property str1005() As String
            Get
                Return ResourceManager.GetString("str1005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prev.
        '''</summary>
        Friend ReadOnly Property str1006() As String
            Get
                Return ResourceManager.GetString("str1006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next.
        '''</summary>
        Friend ReadOnly Property str1007() As String
            Get
                Return ResourceManager.GetString("str1007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calc. segment.
        '''</summary>
        Friend ReadOnly Property str1008() As String
            Get
                Return ResourceManager.GetString("str1008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend ReadOnly Property str1009() As String
            Get
                Return ResourceManager.GetString("str1009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Return.
        '''</summary>
        Friend ReadOnly Property str1010() As String
            Get
                Return ResourceManager.GetString("str1010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re&amp;move Leg.
        '''</summary>
        Friend ReadOnly Property str1011() As String
            Get
                Return ResourceManager.GetString("str1011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend ReadOnly Property str1012() As String
            Get
                Return ResourceManager.GetString("str1012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend ReadOnly Property str1013() As String
            Get
                Return ResourceManager.GetString("str1013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property str1014() As String
            Get
                Return ResourceManager.GetString("str1014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report.
        '''</summary>
        Friend ReadOnly Property str1015() As String
            Get
                Return ResourceManager.GetString("str1015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segment &amp;info.
        '''</summary>
        Friend ReadOnly Property str1016() As String
            Get
                Return ResourceManager.GetString("str1016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WPT:.
        '''</summary>
        Friend ReadOnly Property str1017() As String
            Get
                Return ResourceManager.GetString("str1017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Facility:.
        '''</summary>
        Friend ReadOnly Property str1018() As String
            Get
                Return ResourceManager.GetString("str1018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start point:.
        '''</summary>
        Friend ReadOnly Property str1100() As String
            Get
                Return ResourceManager.GetString("str1100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Altitude:.
        '''</summary>
        Friend ReadOnly Property str1101() As String
            Get
                Return ResourceManager.GetString("str1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MOC:.
        '''</summary>
        Friend ReadOnly Property str1102() As String
            Get
                Return ResourceManager.GetString("str1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bearing....
        '''</summary>
        Friend ReadOnly Property str1103() As String
            Get
                Return ResourceManager.GetString("str1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend ReadOnly Property str1104() As String
            Get
                Return ResourceManager.GetString("str1104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Magnetic.
        '''</summary>
        Friend ReadOnly Property str1105() As String
            Get
                Return ResourceManager.GetString("str1105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manual set.
        '''</summary>
        Friend ReadOnly Property str1106() As String
            Get
                Return ResourceManager.GetString("str1106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On the line of WPT/FIX.
        '''</summary>
        Friend ReadOnly Property str1107() As String
            Get
                Return ResourceManager.GetString("str1107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buffer semiwidth:.
        '''</summary>
        Friend ReadOnly Property str1108() As String
            Get
                Return ResourceManager.GetString("str1108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aircraft category:.
        '''</summary>
        Friend ReadOnly Property str1109() As String
            Get
                Return ResourceManager.GetString("str1109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manoeuvre.
        '''</summary>
        Friend ReadOnly Property str1200() As String
            Get
                Return ResourceManager.GetString("str1200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameters.
        '''</summary>
        Friend ReadOnly Property str1201() As String
            Get
                Return ResourceManager.GetString("str1201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn direction:.
        '''</summary>
        Friend ReadOnly Property str1202() As String
            Get
                Return ResourceManager.GetString("str1202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To the left.
        '''</summary>
        Friend ReadOnly Property str1203() As String
            Get
                Return ResourceManager.GetString("str1203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To the right.
        '''</summary>
        Friend ReadOnly Property str1204() As String
            Get
                Return ResourceManager.GetString("str1204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descent gradient:.
        '''</summary>
        Friend ReadOnly Property str1205() As String
            Get
                Return ResourceManager.GetString("str1205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New course.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Termination mode.
        '''</summary>
        Friend ReadOnly Property str1301() As String
            Get
                Return ResourceManager.GetString("str1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to At a distance from DME.
        '''</summary>
        Friend ReadOnly Property str1302() As String
            Get
                Return ResourceManager.GetString("str1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Before DME.
        '''</summary>
        Friend ReadOnly Property str1303() As String
            Get
                Return ResourceManager.GetString("str1303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to After DME.
        '''</summary>
        Friend ReadOnly Property str1304() As String
            Get
                Return ResourceManager.GetString("str1304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to At the VOR/NDB radial.
        '''</summary>
        Friend ReadOnly Property str1305() As String
            Get
                Return ResourceManager.GetString("str1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overhead WPT.
        '''</summary>
        Friend ReadOnly Property str1306() As String
            Get
                Return ResourceManager.GetString("str1306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to At the given distance.
        '''</summary>
        Friend ReadOnly Property str1307() As String
            Get
                Return ResourceManager.GetString("str1307", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change course up to 90°.
        '''</summary>
        Friend ReadOnly Property str1308() As String
            Get
                Return ResourceManager.GetString("str1308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn variant.
        '''</summary>
        Friend ReadOnly Property str1400() As String
            Get
                Return ResourceManager.GetString("str1400", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Onto set course.
        '''</summary>
        Friend ReadOnly Property str1401() As String
            Get
                Return ResourceManager.GetString("str1401", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Onto set WPT.
        '''</summary>
        Friend ReadOnly Property str1402() As String
            Get
                Return ResourceManager.GetString("str1402", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not all segment points have been defined..
        '''</summary>
        Friend ReadOnly Property str1403() As String
            Get
                Return ResourceManager.GetString("str1403", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend ReadOnly Property str1405() As String
            Get
                Return ResourceManager.GetString("str1405", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend ReadOnly Property str1406() As String
            Get
                Return ResourceManager.GetString("str1406", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elevation.
        '''</summary>
        Friend ReadOnly Property str1407() As String
            Get
                Return ResourceManager.GetString("str1407", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MOC.
        '''</summary>
        Friend ReadOnly Property str1408() As String
            Get
                Return ResourceManager.GetString("str1408", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Req.Alt..
        '''</summary>
        Friend ReadOnly Property str1409() As String
            Get
                Return ResourceManager.GetString("str1409", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No prosedures.
        '''</summary>
        Friend ReadOnly Property str2001() As String
            Get
                Return ResourceManager.GetString("str2001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aerodrome:.
        '''</summary>
        Friend ReadOnly Property str2002() As String
            Get
                Return ResourceManager.GetString("str2002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prosedure group:.
        '''</summary>
        Friend ReadOnly Property str2003() As String
            Get
                Return ResourceManager.GetString("str2003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Area radius:.
        '''</summary>
        Friend ReadOnly Property str2004() As String
            Get
                Return ResourceManager.GetString("str2004", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
