//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMSLServiceClient.CTSDownload {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.teamead.com/ws/sdd", ConfigurationName="CTSDownload.SDDDownloandPortType")]
    public interface SDDDownloandPortType {
        
        // CODEGEN: Generating message contract since the operation downloadAixmMessageFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://www.teamead.com/ws/sdd/SDDDownloandPortType/DownloadAixmMessageFileInput", ReplyAction="http://www.teamead.com/ws/sdd/SDDDownloandPortType/DownloadAixmMessageFileOutput")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileOutput downloadAixmMessageFile(AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileInput request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://www.teamead.com/ws/sdd/SDDDownloandPortType/DownloadAixmMessageFileInput", ReplyAction="http://www.teamead.com/ws/sdd/SDDDownloandPortType/DownloadAixmMessageFileOutput")]
        System.Threading.Tasks.Task<AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileOutput> downloadAixmMessageFileAsync(AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileInput request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.teamead.com/ws/sdd")]
    public partial class GetDownload : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string downloadFileIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string downloadFileId {
            get {
                return this.downloadFileIdField;
            }
            set {
                this.downloadFileIdField = value;
                this.RaisePropertyChanged("downloadFileId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teamead.com/ws/sdd")]
    public partial class AttachedFileType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string checksumField;
        
        private string mimetypeField;
        
        private byte[] contentField;
        
        public AttachedFileType() {
            this.mimetypeField = "text/xml";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string checksum {
            get {
                return this.checksumField;
            }
            set {
                this.checksumField = value;
                this.RaisePropertyChanged("checksum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mimetype {
            get {
                return this.mimetypeField;
            }
            set {
                this.mimetypeField = value;
                this.RaisePropertyChanged("mimetype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.teamead.com/ws/sdd")]
    public partial class DownloadResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusType statusField;
        
        private AttachedFileType logField;
        
        private AttachedFileType downloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AttachedFileType log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("log");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AttachedFileType download {
            get {
                return this.downloadField;
            }
            set {
                this.downloadField = value;
                this.RaisePropertyChanged("download");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teamead.com/ws/sdd")]
    public enum StatusType {
        
        /// <remarks/>
        QUEUED,
        
        /// <remarks/>
        PROCESSING,
        
        /// <remarks/>
        FINISHED,
        
        /// <remarks/>
        FAILED,
        
        /// <remarks/>
        CANCELED,
        
        /// <remarks/>
        PAUSED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadAixmMessageFileInput {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.teamead.com/ws/sdd", Order=0)]
        public AIMSLServiceClient.CTSDownload.GetDownload GetDownload;
        
        public DownloadAixmMessageFileInput() {
        }
        
        public DownloadAixmMessageFileInput(AIMSLServiceClient.CTSDownload.GetDownload GetDownload) {
            this.GetDownload = GetDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadAixmMessageFileOutput {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.teamead.com/ws/sdd", Order=0)]
        public AIMSLServiceClient.CTSDownload.DownloadResponse DownloadResponse;
        
        public DownloadAixmMessageFileOutput() {
        }
        
        public DownloadAixmMessageFileOutput(AIMSLServiceClient.CTSDownload.DownloadResponse DownloadResponse) {
            this.DownloadResponse = DownloadResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SDDDownloandPortTypeChannel : AIMSLServiceClient.CTSDownload.SDDDownloandPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SDDDownloandPortTypeClient : System.ServiceModel.ClientBase<AIMSLServiceClient.CTSDownload.SDDDownloandPortType>, AIMSLServiceClient.CTSDownload.SDDDownloandPortType {
        
        public SDDDownloandPortTypeClient() {
        }
        
        public SDDDownloandPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SDDDownloandPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDDDownloandPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDDDownloandPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileOutput AIMSLServiceClient.CTSDownload.SDDDownloandPortType.downloadAixmMessageFile(AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileInput request) {
            return base.Channel.downloadAixmMessageFile(request);
        }
        
        public AIMSLServiceClient.CTSDownload.DownloadResponse downloadAixmMessageFile(AIMSLServiceClient.CTSDownload.GetDownload GetDownload) {
            AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileInput inValue = new AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileInput();
            inValue.GetDownload = GetDownload;
            AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileOutput retVal = ((AIMSLServiceClient.CTSDownload.SDDDownloandPortType)(this)).downloadAixmMessageFile(inValue);
            return retVal.DownloadResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileOutput> AIMSLServiceClient.CTSDownload.SDDDownloandPortType.downloadAixmMessageFileAsync(AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileInput request) {
            return base.Channel.downloadAixmMessageFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileOutput> downloadAixmMessageFileAsync(AIMSLServiceClient.CTSDownload.GetDownload GetDownload) {
            AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileInput inValue = new AIMSLServiceClient.CTSDownload.DownloadAixmMessageFileInput();
            inValue.GetDownload = GetDownload;
            return ((AIMSLServiceClient.CTSDownload.SDDDownloandPortType)(this)).downloadAixmMessageFileAsync(inValue);
        }
    }
}
