<?xml version="1.0"?>
<Chart_ObjectsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <List xsi:type="ChartElement_SimpleText">
    <Id>e00e7ca3-02f9-4796-839a-f98ecd0e12f8</Id>
    <Name>IsogonalLines</Name>
    <RelatedFeature>IsogonalLines</RelatedFeature>
    <Placed>true</Placed>
    <ReflectionHidden>false</ReflectionHidden>
    <HorizontalAlignment>Left</HorizontalAlignment>
    <VerticalAlignment>Center</VerticalAlignment>
    <TextPosition>Normal</TextPosition>
    <Anchor>
      <X>0</X>
      <Y>0</Y>
    </Anchor>
    <Slope>0</Slope>
    <Font>
      <Bold>false</Bold>
      <FontColor>
        <AncorColor_CMYK>557400832</AncorColor_CMYK>
        <AncorColor_NullColor>false</AncorColor_NullColor>
        <AncorColor_RGB>39087787</AncorColor_RGB>
        <AncorColor_Transparency>255</AncorColor_Transparency>
        <AncorColor_UseWindowsDithering>false</AncorColor_UseWindowsDithering>
      </FontColor>
      <Italic>false</Italic>
      <Name>Arial</Name>
      <Size>10</Size>
      <UnderLine>false</UnderLine>
    </Font>
    <Leading>0</Leading>
    <HaloColor>
      <AncorColor_CMYK>100</AncorColor_CMYK>
      <AncorColor_NullColor>false</AncorColor_NullColor>
      <AncorColor_RGB>33554432</AncorColor_RGB>
      <AncorColor_Transparency>255</AncorColor_Transparency>
      <AncorColor_UseWindowsDithering>false</AncorColor_UseWindowsDithering>
    </HaloColor>
    <HaloMaskSize>0</HaloMaskSize>
    <FillColor>
      <AncorColor_CMYK>100</AncorColor_CMYK>
      <AncorColor_NullColor>false</AncorColor_NullColor>
      <AncorColor_RGB>33554432</AncorColor_RGB>
      <AncorColor_Transparency>255</AncorColor_Transparency>
      <AncorColor_UseWindowsDithering>false</AncorColor_UseWindowsDithering>
    </FillColor>
    <FillStyle>fSNull</FillStyle>
    <TextContents>
      <ArrayOfAncorChartElementWord>
        <AncorChartElementWord>
          <DataSource>
            <Link>Procedure</Link>
            <Condition>Procedure</Condition>
            <Value>ProcedureIdentifier</Value>
          </DataSource>
          <StartSymbol>
            <Text />
            <TextFont>
              <Bold>false</Bold>
              <FontColor>
                <AncorColor_CMYK>557400832</AncorColor_CMYK>
                <AncorColor_NullColor>false</AncorColor_NullColor>
                <AncorColor_RGB>39087787</AncorColor_RGB>
                <AncorColor_Transparency>255</AncorColor_Transparency>
                <AncorColor_UseWindowsDithering>false</AncorColor_UseWindowsDithering>
              </FontColor>
              <Italic>false</Italic>
              <Name>Arial</Name>
              <Size>10</Size>
              <UnderLine>false</UnderLine>
            </TextFont>
          </StartSymbol>
          <EndSymbol>
            <Text />
            <TextFont>
              <Bold>false</Bold>
              <FontColor>
                <AncorColor_CMYK>557400832</AncorColor_CMYK>
                <AncorColor_NullColor>false</AncorColor_NullColor>
                <AncorColor_RGB>39087787</AncorColor_RGB>
                <AncorColor_Transparency>255</AncorColor_Transparency>
                <AncorColor_UseWindowsDithering>false</AncorColor_UseWindowsDithering>
              </FontColor>
              <Italic>false</Italic>
              <Name>Arial</Name>
              <Size>10</Size>
              <UnderLine>false</UnderLine>
            </TextFont>
          </EndSymbol>
          <TextCase>Normal</TextCase>
          <TextValue>TextfromDataSource</TextValue>
          <Font>
            <Bold>false</Bold>
            <FontColor>
              <AncorColor_CMYK>557400832</AncorColor_CMYK>
              <AncorColor_NullColor>false</AncorColor_NullColor>
              <AncorColor_RGB>39087787</AncorColor_RGB>
              <AncorColor_Transparency>255</AncorColor_Transparency>
              <AncorColor_UseWindowsDithering>false</AncorColor_UseWindowsDithering>
            </FontColor>
            <Italic>false</Italic>
            <Name>Arial</Name>
            <Size>10</Size>
            <UnderLine>false</UnderLine>
          </Font>
          <CharacterSpacing>0</CharacterSpacing>
          <CharacterWidth>0</CharacterWidth>
          <Leading>0</Leading>
          <TextPosition>Normal</TextPosition>
          <WordSpacing>0</WordSpacing>
          <Morse>false</Morse>
          <Visible>true</Visible>
        </AncorChartElementWord>
      </ArrayOfAncorChartElementWord>
    </TextContents>
    <CharacterSpacing>0</CharacterSpacing>
    <CharacterWidth>0</CharacterWidth>
    <WordSpacing>100</WordSpacing>
    <TextCase>Normal</TextCase>
    <CoordType>DDMMSSN_1</CoordType>
  </List>
  <ChartType>patc</ChartType>
</Chart_ObjectsList>