//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIP.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIP.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_16 {
            get {
                object obj = ResourceManager.GetObject("calendar_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Data {
            get {
                object obj = ResourceManager.GetObject("Data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;e:GEN-0.1 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:x=&quot;http://www.w3.org/1999/xhtml&quot; id=&quot;GEN-0.1&quot; Toc=&quot;No&quot; Number=&quot;GEN 0.1&quot; xmlns:e=&quot;http://www.eurocontrol.int/xmlns/AIM/eAIP&quot;&gt;
        ///  &lt;e:Title Updated=&quot;No&quot;&gt;PREFACE&lt;/e:Title&gt;
        ///  &lt;e:Sub-section Updated=&quot;No&quot; Toc=&quot;No&quot; Number=&quot;auto&quot;&gt;
        ///    &lt;e:Title Updated=&quot;No&quot;&gt;APPLICABLE ICAO DOCUMENTS&lt;/e:Title&gt;
        ///    &lt;x:div Updated=&quot;No&quot;&gt;{TEST_TEXT}&lt;/x:div&gt;
        ///  &lt;/e:Sub-section&gt;
        ///&lt;/e:GEN-0.1&gt;.
        /// </summary>
        internal static string EV_GEN_0_1_en_GB {
            get {
                return ResourceManager.GetString("EV_GEN_0_1_en_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///
        ///&lt;?eAIP-locales ../locales.xml?&gt;
        ///&lt;e:GEN-2.2 id = &quot;GEN-2.2&quot; xmlns:x = &quot;http://www.w3.org/1999/xhtml&quot; xmlns:e = &quot;http://www.eurocontrol.int/xmlns/AIM/eAIP&quot; xmlns:xlink = &quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;?FM MARKER [FrameAPS Content] PM-0.1,6733708,480596?&gt;
        ///&lt;e:Title id = &quot;GEN220601231355071&quot;&gt; ABBREVIATIONS USED IN AIS PUBLICATIONS&lt;/e:Title&gt;
        ///&lt;x:p id = &quot;GEN220811240840270&quot; class = &quot;Body&quot;&gt;&lt;x:em id = &quot;GEN220811240845172&quot;&gt;Abbreviations marked by an asterisk (*) are eithe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EV_GEN_2_2_en_GB {
            get {
                return ResourceManager.GetString("EV_GEN_2_2_en_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///
        ///&lt;?eAIP-locales ../locales.xml?&gt;
        ///&lt;e:GEN-2.2 id = &quot;GEN-2.2&quot; xmlns:x = &quot;http://www.w3.org/1999/xhtml&quot; xmlns:e = &quot;http://www.eurocontrol.int/xmlns/AIM/eAIP&quot; xmlns:xlink = &quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;?FM MARKER [FrameAPS Content] PM-0.1,6733708,480596?&gt;
        ///&lt;e:Title id = &quot;GEN220601231355071&quot;&gt; AIS PUBLIKĀCIJĀS IZMANTOTĀS ABREVIATŪRAS&lt;/e:Title&gt;
        ///&lt;x:p id = &quot;GEN220811240840270&quot; class = &quot;Body&quot;&gt;Saīsinājumi, kuri ir atzīmēti ar zvaigznīti (*), ir atšķirīgi vai nav atrodami IC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EV_GEN_2_2_lv_LV {
            get {
                return ResourceManager.GetString("EV_GEN_2_2_lv_LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE translations PUBLIC &quot;-//EUROCONTROL//eAIP locales//EN&quot; &quot;../../eAIP-pack/dtd/locales.dtd&quot;&gt;
        ///&lt;!--
        ///    Copyright (c) 2000-2002 EUROCONTROL, all rights reserved.
        ///    This work is subject to the license provided in the file LICENSE.txt.
        ///--&gt;
        ///&lt;!--
        ///	translations.xml: translations of static text used by eAIP transformations.
        ///	$Date: 2011-01-06 12:52:58 +0100 (Thu, 06 Jan 2011) $
        ///	$Revision: 14585 $
        ///--&gt;
        ///&lt;translations xmlns=&quot;http://www.eurocontrol.int/xmlns/AI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locales {
            get {
                return ResourceManager.GetString("locales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off {
            get {
                object obj = ResourceManager.GetObject("off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap on {
            get {
                object obj = ResourceManager.GetObject("on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OutputPack {
            get {
                object obj = ResourceManager.GetObject("OutputPack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SourcePack {
            get {
                object obj = ResourceManager.GetObject("SourcePack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE e:eAIP PUBLIC &quot;-//EUROCONTROL//eAIP DTD 2.0//EN&quot; &quot;../../../eAIP-pack/dtd/eAIP.dtd&quot; [
        ///&lt;!ENTITY eAIP-GEN-0.1 SYSTEM &quot;{COUNTRY}-GEN-0.1-{LANG}.xml&quot;&gt;
        ///&lt;!ENTITY eAIP-GEN-0.2 SYSTEM &quot;{COUNTRY}-GEN-0.2-{LANG}.xml&quot;&gt;
        ///&lt;!ENTITY eAIP-GEN-0.3 SYSTEM &quot;{COUNTRY}-GEN-0.3-{LANG}.xml&quot;&gt;
        ///&lt;!ENTITY eAIP-GEN-0.4 SYSTEM &quot;{COUNTRY}-GEN-0.4-{LANG}.xml&quot;&gt;
        ///&lt;!ENTITY eAIP-GEN-0.5 SYSTEM &quot;{COUNTRY}-GEN-0.5-{LANG}.xml&quot;&gt;
        ///&lt;!ENTITY eAIP-GEN-0.6 SYSTEM &quot;{COUNTRY}-GEN-0.6-{LANG}.xml&quot;&gt;
        ///&lt;!EN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Speciman_eAIP {
            get {
                return ResourceManager.GetString("Speciman_eAIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_bold {
            get {
                object obj = ResourceManager.GetObject("text_bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_italic {
            get {
                object obj = ResourceManager.GetObject("text_italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
