//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aran.PANDA.RNAV.Approach.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aran.PANDA.RNAV.Approach.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HIDE_INFO {
            get {
                object obj = ResourceManager.GetObject("HIDE_INFO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SHOW_INFO {
            get {
                object obj = ResourceManager.GetObject("SHOW_INFO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string str00002 {
            get {
                return ResourceManager.GetString("str00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string str00003 {
            get {
                return ResourceManager.GetString("str00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string str00004 {
            get {
                return ResourceManager.GetString("str00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string str00005 {
            get {
                return ResourceManager.GetString("str00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string str00006 {
            get {
                return ResourceManager.GetString("str00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string str00007 {
            get {
                return ResourceManager.GetString("str00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string str00008 {
            get {
                return ResourceManager.GetString("str00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARP.
        /// </summary>
        internal static string str00010 {
            get {
                return ResourceManager.GetString("str00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWY.
        /// </summary>
        internal static string str00011 {
            get {
                return ResourceManager.GetString("str00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dsgn..
        /// </summary>
        internal static string str00012 {
            get {
                return ResourceManager.GetString("str00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNAV Approach.
        /// </summary>
        internal static string str00033 {
            get {
                return ResourceManager.GetString("str00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report on Obstacles..
        /// </summary>
        internal static string str00109 {
            get {
                return ResourceManager.GetString("str00109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file..
        /// </summary>
        internal static string str00124 {
            get {
                return ResourceManager.GetString("str00124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateral Navigation.
        /// </summary>
        internal static string str00130 {
            get {
                return ResourceManager.GetString("str00130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial parameters.
        /// </summary>
        internal static string str00300 {
            get {
                return ResourceManager.GetString("str00300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final approach course.
        /// </summary>
        internal static string str00301 {
            get {
                return ResourceManager.GetString("str00301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final / Intermediate  Approach.
        /// </summary>
        internal static string str00302 {
            get {
                return ResourceManager.GetString("str00302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Approach SDF.
        /// </summary>
        internal static string str00303 {
            get {
                return ResourceManager.GetString("str00303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Approache SDF.
        /// </summary>
        internal static string str00304 {
            get {
                return ResourceManager.GetString("str00304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight missed approach.
        /// </summary>
        internal static string str00305 {
            get {
                return ResourceManager.GetString("str00305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning missed approach.
        /// </summary>
        internal static string str00306 {
            get {
                return ResourceManager.GetString("str00306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed approach segments.
        /// </summary>
        internal static string str00307 {
            get {
                return ResourceManager.GetString("str00307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string str00308 {
            get {
                return ResourceManager.GetString("str00308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerodrome:.
        /// </summary>
        internal static string str00501 {
            get {
                return ResourceManager.GetString("str00501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure name:.
        /// </summary>
        internal static string str00502 {
            get {
                return ResourceManager.GetString("str00502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft category: up to.
        /// </summary>
        internal static string str00504 {
            get {
                return ResourceManager.GetString("str00504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date:.
        /// </summary>
        internal static string str00505 {
            get {
                return ResourceManager.GetString("str00505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation time:.
        /// </summary>
        internal static string str00506 {
            get {
                return ResourceManager.GetString("str00506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distances are in.
        /// </summary>
        internal static string str00507 {
            get {
                return ResourceManager.GetString("str00507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevations and heights are in.
        /// </summary>
        internal static string str00508 {
            get {
                return ResourceManager.GetString("str00508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeds are in.
        /// </summary>
        internal static string str00509 {
            get {
                return ResourceManager.GetString("str00509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure geometry.
        /// </summary>
        internal static string str00517 {
            get {
                return ResourceManager.GetString("str00517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The departure procedure overall length.
        /// </summary>
        internal static string str00519 {
            get {
                return ResourceManager.GetString("str00519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string str00564 {
            get {
                return ResourceManager.GetString("str00564", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string str00565 {
            get {
                return ResourceManager.GetString("str00565", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude of the circle center.
        /// </summary>
        internal static string str00566 {
            get {
                return ResourceManager.GetString("str00566", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude of the circle center.
        /// </summary>
        internal static string str00567 {
            get {
                return ResourceManager.GetString("str00567", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string str00568 {
            get {
                return ResourceManager.GetString("str00568", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string str00569 {
            get {
                return ResourceManager.GetString("str00569", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning radius.
        /// </summary>
        internal static string str00572 {
            get {
                return ResourceManager.GetString("str00572", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn direction.
        /// </summary>
        internal static string str00573 {
            get {
                return ResourceManager.GetString("str00573", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string str00574 {
            get {
                return ResourceManager.GetString("str00574", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string str00575 {
            get {
                return ResourceManager.GetString("str00575", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle of the turn.
        /// </summary>
        internal static string str00576 {
            get {
                return ResourceManager.GetString("str00576", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True course.
        /// </summary>
        internal static string str00577 {
            get {
                return ResourceManager.GetString("str00577", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance to the next point.
        /// </summary>
        internal static string str00578 {
            get {
                return ResourceManager.GetString("str00578", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn arc length.
        /// </summary>
        internal static string str00579 {
            get {
                return ResourceManager.GetString("str00579", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWY:.
        /// </summary>
        internal static string str01000 {
            get {
                return ResourceManager.GetString("str01000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWY direction:.
        /// </summary>
        internal static string str01001 {
            get {
                return ResourceManager.GetString("str01001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Brg:.
        /// </summary>
        internal static string str01002 {
            get {
                return ResourceManager.GetString("str01002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Brg:.
        /// </summary>
        internal static string str01003 {
            get {
                return ResourceManager.GetString("str01003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation:.
        /// </summary>
        internal static string str01004 {
            get {
                return ResourceManager.GetString("str01004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCH:.
        /// </summary>
        internal static string str01005 {
            get {
                return ResourceManager.GetString("str01005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Category:.
        /// </summary>
        internal static string str01006 {
            get {
                return ResourceManager.GetString("str01006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupName.
        /// </summary>
        internal static string str01007 {
            get {
                return ResourceManager.GetString("str01007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LNAV.
        /// </summary>
        internal static string str01008 {
            get {
                return ResourceManager.GetString("str01008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APV-BARO VNAV.
        /// </summary>
        internal static string str01009 {
            get {
                return ResourceManager.GetString("str01009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCH is specified relatively to Aerodrome elevation.
        /// </summary>
        internal static string str01010 {
            get {
                return ResourceManager.GetString("str01010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCH is specified relatively to THR elevation.
        /// </summary>
        internal static string str01011 {
            get {
                return ResourceManager.GetString("str01011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string str02000 {
            get {
                return ResourceManager.GetString("str02000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select anchor point.
        /// </summary>
        internal static string str02001 {
            get {
                return ResourceManager.GetString("str02001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose track.
        /// </summary>
        internal static string str02002 {
            get {
                return ResourceManager.GetString("str02002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligned.
        /// </summary>
        internal static string str02003 {
            get {
                return ResourceManager.GetString("str02003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-aligned.
        /// </summary>
        internal static string str02004 {
            get {
                return ResourceManager.GetString("str02004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Abeam C/L on
        /// 1400 m from THR.
        /// </summary>
        internal static string str02005 {
            get {
                return ResourceManager.GetString("str02005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Point:.
        /// </summary>
        internal static string str02006 {
            get {
                return ResourceManager.GetString("str02006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select course.
        /// </summary>
        internal static string str02007 {
            get {
                return ResourceManager.GetString("str02007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select second point.
        /// </summary>
        internal static string str02008 {
            get {
                return ResourceManager.GetString("str02008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from THR:.
        /// </summary>
        internal static string str02009 {
            get {
                return ResourceManager.GetString("str02009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abeam Distance at 1400m:.
        /// </summary>
        internal static string str02010 {
            get {
                return ResourceManager.GetString("str02010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Point:.
        /// </summary>
        internal static string str02011 {
            get {
                return ResourceManager.GetString("str02011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. intersection
        ///distance:.
        /// </summary>
        internal static string str02012 {
            get {
                return ResourceManager.GetString("str02012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True bearing:.
        /// </summary>
        internal static string str02013 {
            get {
                return ResourceManager.GetString("str02013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Fixed Point:.
        /// </summary>
        internal static string str02014 {
            get {
                return ResourceManager.GetString("str02014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal OCA:.
        /// </summary>
        internal static string str02015 {
            get {
                return ResourceManager.GetString("str02015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal OCH:.
        /// </summary>
        internal static string str02016 {
            get {
                return ResourceManager.GetString("str02016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Along C/L further
        /// than 1400 m from THR.
        /// </summary>
        internal static string str02017 {
            get {
                return ResourceManager.GetString("str02017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight in.
        /// </summary>
        internal static string str02018 {
            get {
                return ResourceManager.GetString("str02018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circling.
        /// </summary>
        internal static string str02019 {
            get {
                return ResourceManager.GetString("str02019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Point:.
        /// </summary>
        internal static string str02020 {
            get {
                return ResourceManager.GetString("str02020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from ARP:.
        /// </summary>
        internal static string str02021 {
            get {
                return ResourceManager.GetString("str02021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Direction defined by .
        /// </summary>
        internal static string str02022 {
            get {
                return ResourceManager.GetString("str02022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select interval:.
        /// </summary>
        internal static string str02023 {
            get {
                return ResourceManager.GetString("str02023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True course:.
        /// </summary>
        internal static string str02024 {
            get {
                return ResourceManager.GetString("str02024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPT:.
        /// </summary>
        internal static string str02025 {
            get {
                return ResourceManager.GetString("str02025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string str02026 {
            get {
                return ResourceManager.GetString("str02026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From true bearing °.
        /// </summary>
        internal static string str02027 {
            get {
                return ResourceManager.GetString("str02027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To true bearing °.
        /// </summary>
        internal static string str02028 {
            get {
                return ResourceManager.GetString("str02028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal.
        /// </summary>
        internal static string str02029 {
            get {
                return ResourceManager.GetString("str02029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnidirectional.
        /// </summary>
        internal static string str02030 {
            get {
                return ResourceManager.GetString("str02030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desirable limit.
        /// </summary>
        internal static string str02031 {
            get {
                return ResourceManager.GetString("str02031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxsimum limit.
        /// </summary>
        internal static string str02032 {
            get {
                return ResourceManager.GetString("str02032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final approach / FAF location (GNSS RNP APCH) .
        /// </summary>
        internal static string str03001 {
            get {
                return ResourceManager.GetString("str03001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate APCH segment .
        /// </summary>
        internal static string str03002 {
            get {
                return ResourceManager.GetString("str03002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF/SDF location .
        /// </summary>
        internal static string str03003 {
            get {
                return ResourceManager.GetString("str03003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By FAF Altitude:.
        /// </summary>
        internal static string str03004 {
            get {
                return ResourceManager.GetString("str03004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By FAF-THR Distance:.
        /// </summary>
        internal static string str03005 {
            get {
                return ResourceManager.GetString("str03005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From List:.
        /// </summary>
        internal static string str03006 {
            get {
                return ResourceManager.GetString("str03006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent gradient:.
        /// </summary>
        internal static string str03007 {
            get {
                return ResourceManager.GetString("str03007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNSS.
        /// </summary>
        internal static string str03008 {
            get {
                return ResourceManager.GetString("str03008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DME/DME.
        /// </summary>
        internal static string str03009 {
            get {
                return ResourceManager.GetString("str03009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 2 DME.
        /// </summary>
        internal static string str03010 {
            get {
                return ResourceManager.GetString("str03010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBN Type:.
        /// </summary>
        internal static string str03011 {
            get {
                return ResourceManager.GetString("str03011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAS:.
        /// </summary>
        internal static string str03012 {
            get {
                return ResourceManager.GetString("str03012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By distance and azimuth.
        /// </summary>
        internal static string str03013 {
            get {
                return ResourceManager.GetString("str03013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From List.
        /// </summary>
        internal static string str03014 {
            get {
                return ResourceManager.GetString("str03014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance
        ///from FAF:.
        /// </summary>
        internal static string str03015 {
            get {
                return ResourceManager.GetString("str03015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound true
        ///course at FAF:.
        /// </summary>
        internal static string str03016 {
            get {
                return ResourceManager.GetString("str03016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call sign:.
        /// </summary>
        internal static string str03017 {
            get {
                return ResourceManager.GetString("str03017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned max
        ///turn angle:.
        /// </summary>
        internal static string str03018 {
            get {
                return ResourceManager.GetString("str03018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligned course.
        /// </summary>
        internal static string str03019 {
            get {
                return ResourceManager.GetString("str03019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAP altitude violated by obstacle clearance within intermediate approach segment..
        /// </summary>
        internal static string str03020 {
            get {
                return ResourceManager.GetString("str03020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as SDF.
        /// </summary>
        internal static string str03021 {
            get {
                return ResourceManager.GetString("str03021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCA.
        /// </summary>
        internal static string str03022 {
            get {
                return ResourceManager.GetString("str03022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCH.
        /// </summary>
        internal static string str03023 {
            get {
                return ResourceManager.GetString("str03023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominant obstacle ID:.
        /// </summary>
        internal static string str03024 {
            get {
                return ResourceManager.GetString("str03024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string str03025 {
            get {
                return ResourceManager.GetString("str03025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF Altitude:.
        /// </summary>
        internal static string str03026 {
            get {
                return ResourceManager.GetString("str03026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SDF.
        /// </summary>
        internal static string str04001 {
            get {
                return ResourceManager.GetString("str04001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By altitude:.
        /// </summary>
        internal static string str04002 {
            get {
                return ResourceManager.GetString("str04002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By distance from THR:.
        /// </summary>
        internal static string str04003 {
            get {
                return ResourceManager.GetString("str04003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from list:.
        /// </summary>
        internal static string str04004 {
            get {
                return ResourceManager.GetString("str04004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string str04005 {
            get {
                return ResourceManager.GetString("str04005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string str04006 {
            get {
                return ResourceManager.GetString("str04006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF/SDF location.
        /// </summary>
        internal static string str05001 {
            get {
                return ResourceManager.GetString("str05001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By distance from SDF:.
        /// </summary>
        internal static string str05002 {
            get {
                return ResourceManager.GetString("str05002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from list:.
        /// </summary>
        internal static string str05003 {
            get {
                return ResourceManager.GetString("str05003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance
        ///from SDF:.
        /// </summary>
        internal static string str05004 {
            get {
                return ResourceManager.GetString("str05004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MAPt .
        /// </summary>
        internal static string str06001 {
            get {
                return ResourceManager.GetString("str06001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By distance from THR:.
        /// </summary>
        internal static string str06002 {
            get {
                return ResourceManager.GetString("str06002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from list:.
        /// </summary>
        internal static string str06003 {
            get {
                return ResourceManager.GetString("str06003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOC-MAPt
        /// Distance:.
        /// </summary>
        internal static string str06004 {
            get {
                return ResourceManager.GetString("str06004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FA OCA:.
        /// </summary>
        internal static string str06005 {
            get {
                return ResourceManager.GetString("str06005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FA OCH:.
        /// </summary>
        internal static string str06006 {
            get {
                return ResourceManager.GetString("str06006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA OCA:.
        /// </summary>
        internal static string str06007 {
            get {
                return ResourceManager.GetString("str06007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA Intermediate
        /// phase length:.
        /// </summary>
        internal static string str06008 {
            get {
                return ResourceManager.GetString("str06008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA climb
        /// gradient:.
        /// </summary>
        internal static string str06009 {
            get {
                return ResourceManager.GetString("str06009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caused by:.
        /// </summary>
        internal static string str06010 {
            get {
                return ResourceManager.GetString("str06010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAHF-MAPt
        /// distance:.
        /// </summary>
        internal static string str06011 {
            get {
                return ResourceManager.GetString("str06011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. MAHF
        /// altitude:.
        /// </summary>
        internal static string str06012 {
            get {
                return ResourceManager.GetString("str06012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to turning missed approach.
        /// </summary>
        internal static string str06013 {
            get {
                return ResourceManager.GetString("str06013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  End of MA .
        /// </summary>
        internal static string str06014 {
            get {
                return ResourceManager.GetString("str06014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA Final
        ///phase length:.
        /// </summary>
        internal static string str06015 {
            get {
                return ResourceManager.GetString("str06015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Altitude:.
        /// </summary>
        internal static string str06016 {
            get {
                return ResourceManager.GetString("str06016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn at:.
        /// </summary>
        internal static string str07002 {
            get {
                return ResourceManager.GetString("str07002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank angle:.
        /// </summary>
        internal static string str07003 {
            get {
                return ResourceManager.GetString("str07003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn to:.
        /// </summary>
        internal static string str07004 {
            get {
                return ResourceManager.GetString("str07004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAS:.
        /// </summary>
        internal static string str07005 {
            get {
                return ResourceManager.GetString("str07005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP-MAPt
        ///distance:.
        /// </summary>
        internal static string str07006 {
            get {
                return ResourceManager.GetString("str07006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminry
        ///Turn Altitude:.
        /// </summary>
        internal static string str07007 {
            get {
                return ResourceManager.GetString("str07007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary
        ///OCH:.
        /// </summary>
        internal static string str07008 {
            get {
                return ResourceManager.GetString("str07008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination
        ///Altitude:.
        /// </summary>
        internal static string str07009 {
            get {
                return ResourceManager.GetString("str07009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Turn
        ///Altitude:.
        /// </summary>
        internal static string str07010 {
            get {
                return ResourceManager.GetString("str07010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final OCA:.
        /// </summary>
        internal static string str07011 {
            get {
                return ResourceManager.GetString("str07011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fly mode:.
        /// </summary>
        internal static string str07012 {
            get {
                return ResourceManager.GetString("str07012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P &amp;&amp; T:.
        /// </summary>
        internal static string str07013 {
            get {
                return ResourceManager.GetString("str07013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significiant
        ///obstacle:.
        /// </summary>
        internal static string str07014 {
            get {
                return ResourceManager.GetString("str07014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existinc point.
        /// </summary>
        internal static string str07015 {
            get {
                return ResourceManager.GetString("str07015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        internal static string str07016 {
            get {
                return ResourceManager.GetString("str07016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPT:.
        /// </summary>
        internal static string str07017 {
            get {
                return ResourceManager.GetString("str07017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance
        ///from TP:.
        /// </summary>
        internal static string str07018 {
            get {
                return ResourceManager.GetString("str07018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course:.
        /// </summary>
        internal static string str07019 {
            get {
                return ResourceManager.GetString("str07019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment direction defined by.
        /// </summary>
        internal static string str08001 {
            get {
                return ResourceManager.GetString("str08001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment end WPT position defined by.
        /// </summary>
        internal static string str08002 {
            get {
                return ResourceManager.GetString("str08002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment end WPT construction parameters.
        /// </summary>
        internal static string str08003 {
            get {
                return ResourceManager.GetString("str08003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True course:.
        /// </summary>
        internal static string str08004 {
            get {
                return ResourceManager.GetString("str08004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPT:.
        /// </summary>
        internal static string str08005 {
            get {
                return ResourceManager.GetString("str08005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn to:.
        /// </summary>
        internal static string str08006 {
            get {
                return ResourceManager.GetString("str08006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from
        ///current WPT:.
        /// </summary>
        internal static string str08007 {
            get {
                return ResourceManager.GetString("str08007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPT:.
        /// </summary>
        internal static string str08008 {
            get {
                return ResourceManager.GetString("str08008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPT name:.
        /// </summary>
        internal static string str08009 {
            get {
                return ResourceManager.GetString("str08009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Type:.
        /// </summary>
        internal static string str08010 {
            get {
                return ResourceManager.GetString("str08010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fly mode:.
        /// </summary>
        internal static string str08011 {
            get {
                return ResourceManager.GetString("str08011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBN type:.
        /// </summary>
        internal static string str08012 {
            get {
                return ResourceManager.GetString("str08012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 2 DME.
        /// </summary>
        internal static string str08013 {
            get {
                return ResourceManager.GetString("str08013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P &amp;&amp; T:.
        /// </summary>
        internal static string str08014 {
            get {
                return ResourceManager.GetString("str08014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight time:.
        /// </summary>
        internal static string str08015 {
            get {
                return ResourceManager.GetString("str08015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCA:.
        /// </summary>
        internal static string str08016 {
            get {
                return ResourceManager.GetString("str08016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearance calculation.
        /// </summary>
        internal static string str10000 {
            get {
                return ResourceManager.GetString("str10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count : .
        /// </summary>
        internal static string str10001 {
            get {
                return ResourceManager.GetString("str10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string str10002 {
            get {
                return ResourceManager.GetString("str10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string str10003 {
            get {
                return ResourceManager.GetString("str10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        internal static string str10004 {
            get {
                return ResourceManager.GetString("str10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA Turn area.
        /// </summary>
        internal static string str10007 {
            get {
                return ResourceManager.GetString("str10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current segment.
        /// </summary>
        internal static string str10008 {
            get {
                return ResourceManager.GetString("str10008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segments.
        /// </summary>
        internal static string str10009 {
            get {
                return ResourceManager.GetString("str10009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circling area.
        /// </summary>
        internal static string str10010 {
            get {
                return ResourceManager.GetString("str10010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate approach.
        /// </summary>
        internal static string str10011 {
            get {
                return ResourceManager.GetString("str10011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate significant.
        /// </summary>
        internal static string str10012 {
            get {
                return ResourceManager.GetString("str10012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final approach.
        /// </summary>
        internal static string str10013 {
            get {
                return ResourceManager.GetString("str10013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final SDF 1.
        /// </summary>
        internal static string str10014 {
            get {
                return ResourceManager.GetString("str10014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final SDF 2.
        /// </summary>
        internal static string str10015 {
            get {
                return ResourceManager.GetString("str10015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate SDF 1.
        /// </summary>
        internal static string str10016 {
            get {
                return ResourceManager.GetString("str10016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate SDF 2.
        /// </summary>
        internal static string str10017 {
            get {
                return ResourceManager.GetString("str10017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight MA.
        /// </summary>
        internal static string str10018 {
            get {
                return ResourceManager.GetString("str10018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA straight segment/TIA.
        /// </summary>
        internal static string str10019 {
            get {
                return ResourceManager.GetString("str10019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name.
        /// </summary>
        internal static string str10020 {
            get {
                return ResourceManager.GetString("str10020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string str10021 {
            get {
                return ResourceManager.GetString("str10021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string str10022 {
            get {
                return ResourceManager.GetString("str10022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC.
        /// </summary>
        internal static string str10023 {
            get {
                return ResourceManager.GetString("str10023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. OCH.
        /// </summary>
        internal static string str10024 {
            get {
                return ResourceManager.GetString("str10024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry type.
        /// </summary>
        internal static string str10025 {
            get {
                return ResourceManager.GetString("str10025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. desc. grad..
        /// </summary>
        internal static string str10026 {
            get {
                return ResourceManager.GetString("str10026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string str10027 {
            get {
                return ResourceManager.GetString("str10027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string str10028 {
            get {
                return ResourceManager.GetString("str10028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string str10029 {
            get {
                return ResourceManager.GetString("str10029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored by 15 %.
        /// </summary>
        internal static string str10030 {
            get {
                return ResourceManager.GetString("str10030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC 30.
        /// </summary>
        internal static string str10031 {
            get {
                return ResourceManager.GetString("str10031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC 50.
        /// </summary>
        internal static string str10032 {
            get {
                return ResourceManager.GetString("str10032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Altitude.
        /// </summary>
        internal static string str10033 {
            get {
                return ResourceManager.GetString("str10033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string str10034 {
            get {
                return ResourceManager.GetString("str10034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual MOC.
        /// </summary>
        internal static string str10035 {
            get {
                return ResourceManager.GetString("str10035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from SOC.
        /// </summary>
        internal static string str10036 {
            get {
                return ResourceManager.GetString("str10036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from KK/TIA.
        /// </summary>
        internal static string str10037 {
            get {
                return ResourceManager.GetString("str10037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. MOCA.
        /// </summary>
        internal static string str10038 {
            get {
                return ResourceManager.GetString("str10038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string str10039 {
            get {
                return ResourceManager.GetString("str10039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string str10040 {
            get {
                return ResourceManager.GetString("str10040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string str10041 {
            get {
                return ResourceManager.GetString("str10041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d0.
        /// </summary>
        internal static string str10042 {
            get {
                return ResourceManager.GetString("str10042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d0Sum,.
        /// </summary>
        internal static string str10043 {
            get {
                return ResourceManager.GetString("str10043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. H.
        /// </summary>
        internal static string str10044 {
            get {
                return ResourceManager.GetString("str10044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. OCA.
        /// </summary>
        internal static string str10045 {
            get {
                return ResourceManager.GetString("str10045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string str10046 {
            get {
                return ResourceManager.GetString("str10046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string str10047 {
            get {
                return ResourceManager.GetString("str10047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count : .
        /// </summary>
        internal static string str10048 {
            get {
                return ResourceManager.GetString("str10048", resourceCulture);
            }
        }
    }
}
