//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aran.PANDA.RNAV.PBNAPVBaroVNav.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aran.PANDA.RNAV.PBNAPVBaroVNav.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HIDE_INFO {
            get {
                object obj = ResourceManager.GetObject("HIDE_INFO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SHOW_INFO {
            get {
                object obj = ResourceManager.GetObject("SHOW_INFO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Prev.
        /// </summary>
        internal static string str00002 {
            get {
                return ResourceManager.GetString("str00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        internal static string str00003 {
            get {
                return ResourceManager.GetString("str00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string str00004 {
            get {
                return ResourceManager.GetString("str00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string str00005 {
            get {
                return ResourceManager.GetString("str00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Report.
        /// </summary>
        internal static string str00006 {
            get {
                return ResourceManager.GetString("str00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string str00007 {
            get {
                return ResourceManager.GetString("str00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string str00008 {
            get {
                return ResourceManager.GetString("str00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APV / Baro-VNAV.
        /// </summary>
        internal static string str00033 {
            get {
                return ResourceManager.GetString("str00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerodrome.
        /// </summary>
        internal static string str00100 {
            get {
                return ResourceManager.GetString("str00100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure.
        /// </summary>
        internal static string str00101 {
            get {
                return ResourceManager.GetString("str00101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        internal static string str00102 {
            get {
                return ResourceManager.GetString("str00102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation time.
        /// </summary>
        internal static string str00103 {
            get {
                return ResourceManager.GetString("str00103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distances are in .
        /// </summary>
        internal static string str00104 {
            get {
                return ResourceManager.GetString("str00104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevations and heights are in .
        /// </summary>
        internal static string str00105 {
            get {
                return ResourceManager.GetString("str00105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeds are in .
        /// </summary>
        internal static string str00106 {
            get {
                return ResourceManager.GetString("str00106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure geometry.
        /// </summary>
        internal static string str00107 {
            get {
                return ResourceManager.GetString("str00107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure overall length.
        /// </summary>
        internal static string str00108 {
            get {
                return ResourceManager.GetString("str00108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report on Obstacles..
        /// </summary>
        internal static string str00109 {
            get {
                return ResourceManager.GetString("str00109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string str00110 {
            get {
                return ResourceManager.GetString("str00110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string str00111 {
            get {
                return ResourceManager.GetString("str00111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude of the circle center.
        /// </summary>
        internal static string str00112 {
            get {
                return ResourceManager.GetString("str00112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude of the circle center.
        /// </summary>
        internal static string str00113 {
            get {
                return ResourceManager.GetString("str00113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string str00114 {
            get {
                return ResourceManager.GetString("str00114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string str00115 {
            get {
                return ResourceManager.GetString("str00115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True course.
        /// </summary>
        internal static string str00116 {
            get {
                return ResourceManager.GetString("str00116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning radius.
        /// </summary>
        internal static string str00117 {
            get {
                return ResourceManager.GetString("str00117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn direction.
        /// </summary>
        internal static string str00118 {
            get {
                return ResourceManager.GetString("str00118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to right.
        /// </summary>
        internal static string str00119 {
            get {
                return ResourceManager.GetString("str00119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to left.
        /// </summary>
        internal static string str00120 {
            get {
                return ResourceManager.GetString("str00120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle of the turn.
        /// </summary>
        internal static string str00121 {
            get {
                return ResourceManager.GetString("str00121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn arc length.
        /// </summary>
        internal static string str00122 {
            get {
                return ResourceManager.GetString("str00122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance to the next point.
        /// </summary>
        internal static string str00123 {
            get {
                return ResourceManager.GetString("str00123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file..
        /// </summary>
        internal static string str00124 {
            get {
                return ResourceManager.GetString("str00124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWY.
        /// </summary>
        internal static string str01000 {
            get {
                return ResourceManager.GetString("str01000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Category:.
        /// </summary>
        internal static string str01001 {
            get {
                return ResourceManager.GetString("str01001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWY Direction.
        /// </summary>
        internal static string str01002 {
            get {
                return ResourceManager.GetString("str01002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string str01003 {
            get {
                return ResourceManager.GetString("str01003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Brg:.
        /// </summary>
        internal static string str01004 {
            get {
                return ResourceManager.GetString("str01004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag Brg:.
        /// </summary>
        internal static string str01005 {
            get {
                return ResourceManager.GetString("str01005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation:.
        /// </summary>
        internal static string str01006 {
            get {
                return ResourceManager.GetString("str01006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearway:.
        /// </summary>
        internal static string str01007 {
            get {
                return ResourceManager.GetString("str01007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght:.
        /// </summary>
        internal static string str01008 {
            get {
                return ResourceManager.GetString("str01008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altimeter
        ///margin:.
        /// </summary>
        internal static string str01009 {
            get {
                return ResourceManager.GetString("str01009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest
        ///temperature:.
        /// </summary>
        internal static string str01010 {
            get {
                return ResourceManager.GetString("str01010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA termination
        ///distance:.
        /// </summary>
        internal static string str01011 {
            get {
                return ResourceManager.GetString("str01011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APV segment.
        /// </summary>
        internal static string str02000 {
            get {
                return ResourceManager.GetString("str02000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAP altitude:.
        /// </summary>
        internal static string str02001 {
            get {
                return ResourceManager.GetString("str02001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAP-THR distance:.
        /// </summary>
        internal static string str02002 {
            get {
                return ResourceManager.GetString("str02002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA climp gradient:.
        /// </summary>
        internal static string str02003 {
            get {
                return ResourceManager.GetString("str02003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPA:.
        /// </summary>
        internal static string str02004 {
            get {
                return ResourceManager.GetString("str02004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature correction:.
        /// </summary>
        internal static string str02005 {
            get {
                return ResourceManager.GetString("str02005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCH:.
        /// </summary>
        internal static string str02006 {
            get {
                return ResourceManager.GetString("str02006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAS slope:.
        /// </summary>
        internal static string str02007 {
            get {
                return ResourceManager.GetString("str02007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAS&apos; slope:.
        /// </summary>
        internal static string str02008 {
            get {
                return ResourceManager.GetString("str02008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAS&quot; slope:.
        /// </summary>
        internal static string str02009 {
            get {
                return ResourceManager.GetString("str02009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPt_Parameters_.
        /// </summary>
        internal static string str02010 {
            get {
                return ResourceManager.GetString("str02010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPt fromTHR position:.
        /// </summary>
        internal static string str02011 {
            get {
                return ResourceManager.GetString("str02011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOC from THR position:.
        /// </summary>
        internal static string str02012 {
            get {
                return ResourceManager.GetString("str02012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interm MA Lenght:.
        /// </summary>
        internal static string str02013 {
            get {
                return ResourceManager.GetString("str02013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z surface origin:.
        /// </summary>
        internal static string str02014 {
            get {
                return ResourceManager.GetString("str02014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staight missed approach is impossible.
        /// </summary>
        internal static string str02030 {
            get {
                return ResourceManager.GetString("str02030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D.
        /// </summary>
        internal static string str02031 {
            get {
                return ResourceManager.GetString("str02031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Approach.
        /// </summary>
        internal static string str03000 {
            get {
                return ResourceManager.GetString("str03000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF distance from FAP:.
        /// </summary>
        internal static string str03001 {
            get {
                return ResourceManager.GetString("str03001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF altitude:.
        /// </summary>
        internal static string str03002 {
            get {
                return ResourceManager.GetString("str03002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent gradient:.
        /// </summary>
        internal static string str03003 {
            get {
                return ResourceManager.GetString("str03003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned max turn angle at IF:.
        /// </summary>
        internal static string str03004 {
            get {
                return ResourceManager.GetString("str03004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal segment:.
        /// </summary>
        internal static string str03005 {
            get {
                return ResourceManager.GetString("str03005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate approach IAS:.
        /// </summary>
        internal static string str03006 {
            get {
                return ResourceManager.GetString("str03006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearance calculation.
        /// </summary>
        internal static string str10000 {
            get {
                return ResourceManager.GetString("str10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APV Segment.
        /// </summary>
        internal static string str11000 {
            get {
                return ResourceManager.GetString("str11000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string str11001 {
            get {
                return ResourceManager.GetString("str11001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string str11002 {
            get {
                return ResourceManager.GetString("str11002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H surface.
        /// </summary>
        internal static string str11003 {
            get {
                return ResourceManager.GetString("str11003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H above treshold .
        /// </summary>
        internal static string str11004 {
            get {
                return ResourceManager.GetString("str11004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective height.
        /// </summary>
        internal static string str11005 {
            get {
                return ResourceManager.GetString("str11005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penetration.
        /// </summary>
        internal static string str11006 {
            get {
                return ResourceManager.GetString("str11006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary area coefficient.
        /// </summary>
        internal static string str11007 {
            get {
                return ResourceManager.GetString("str11007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. OCH.
        /// </summary>
        internal static string str11008 {
            get {
                return ResourceManager.GetString("str11008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANS-OPS OCH.
        /// </summary>
        internal static string str11009 {
            get {
                return ResourceManager.GetString("str11009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string str11010 {
            get {
                return ResourceManager.GetString("str11010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string str11011 {
            get {
                return ResourceManager.GetString("str11011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        internal static string str11012 {
            get {
                return ResourceManager.GetString("str11012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string str11013 {
            get {
                return ResourceManager.GetString("str11013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate approach.
        /// </summary>
        internal static string str12000 {
            get {
                return ResourceManager.GetString("str12000", resourceCulture);
            }
        }
    }
}
