//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aran.PANDA.Conventional.Racetrack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aran.PANDA.Conventional.Racetrack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport/Heliport.
        /// </summary>
        internal static string AirportHeliport {
            get {
                return ResourceManager.GetString("AirportHeliport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, at first, define AirportHeliport in menu Tools-&gt;Options.
        /// </summary>
        internal static string AirportHeliport_Definition_Error {
            get {
                return ResourceManager.GetString("AirportHeliport_Definition_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apply {
            get {
                object obj = ResourceManager.GetObject("apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backward {
            get {
                object obj = ResourceManager.GetObject("Backward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, define designated point a bit further or reduce other parameters.
        /// </summary>
        internal static string Define_Pnt_Far {
            get {
                return ResourceManager.GetString("Define_Pnt_Far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap documents {
            get {
                object obj = ResourceManager.GetObject("documents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Forward {
            get {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding/Racetrack couldn&apos;t be created on this point. Because of being on not covered area by navaid.
        /// </summary>
        internal static string Holding_Error {
            get {
                return ResourceManager.GetString("Holding_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Report.
        /// </summary>
        internal static string MainController_SaveReport__Report {
            get {
                return ResourceManager.GetString("MainController_SaveReport__Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Conventional .
        /// </summary>
        internal static string MainController_SaveReport_Save_Conventional_ {
            get {
                return ResourceManager.GetString("MainController_SaveReport_Save_Conventional_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conventional Holding.
        /// </summary>
        internal static string MainController_Startup_Conventional_Holding {
            get {
                return ResourceManager.GetString("MainController_Startup_Conventional_Holding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conventional Racetrack.
        /// </summary>
        internal static string MainController_Startup_Conventional_Racetrack {
            get {
                return ResourceManager.GetString("MainController_Startup_Conventional_Racetrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhead.
        /// </summary>
        internal static string MainController_Startup_Overhead {
            get {
                return ResourceManager.GetString("MainController_Startup_Overhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOR/DME.
        /// </summary>
        internal static string MainController_Startup_VOR_DME {
            get {
                return ResourceManager.GetString("MainController_Startup_VOR_DME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOR/VOR.
        /// </summary>
        internal static string MainController_Startup_VOR_VOR {
            get {
                return ResourceManager.GetString("MainController_Startup_VOR_VOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point couldn&apos;t be defined at this location.
        /// </summary>
        internal static string Pnt_Definition_Warning {
            get {
                return ResourceManager.GetString("Pnt_Definition_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not founde Procedure type !.
        /// </summary>
        internal static string Proc_Type_Not_Found {
            get {
                return ResourceManager.GetString("Proc_Type_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing (Mag.).
        /// </summary>
        internal static string Radial_NDB {
            get {
                return ResourceManager.GetString("Radial_NDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial (Mag.).
        /// </summary>
        internal static string Radial_VOR {
            get {
                return ResourceManager.GetString("Radial_VOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap risk_final_tf {
            get {
                object obj = ResourceManager.GetObject("risk final_tf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time should be within 1-1.5 minutes (depends on altitude).
        /// </summary>
        internal static string Time_Tooltip_Holding {
            get {
                return ResourceManager.GetString("Time_Tooltip_Holding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time should be within 1-3 minutes.
        /// </summary>
        internal static string Time_Tooltip_Racetrack {
            get {
                return ResourceManager.GetString("Time_Tooltip_Racetrack", resourceCulture);
            }
        }
    }
}
