// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("2.0.5.151")]
[assembly: AssemblyFileVersion("2.0.5.151")]
[assembly: AssemblyCompany("R.I.S.K.")]
[assembly: AssemblyCopyright("Copyright © R.I.S.K., 2014-2015")]


 
 
