//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aran.PANDA.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aran.PANDA.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string DistanceUnitKm {
            get {
                return ResourceManager.GetString("DistanceUnitKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NM.
        /// </summary>
        internal static string DistanceUnitNM {
            get {
                return ResourceManager.GetString("DistanceUnitNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft/min.
        /// </summary>
        internal static string DSpeedUnitFt_Min {
            get {
                return ResourceManager.GetString("DSpeedUnitFt_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/min.
        /// </summary>
        internal static string DSpeedUnitM_Min {
            get {
                return ResourceManager.GetString("DSpeedUnitM_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string HeightUnitFt {
            get {
                return ResourceManager.GetString("HeightUnitFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string HeightUnitM {
            get {
                return ResourceManager.GetString("HeightUnitM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        internal static string SpeedUnitKm_H {
            get {
                return ResourceManager.GetString("SpeedUnitKm_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kt.
        /// </summary>
        internal static string SpeedUnitKt {
            get {
                return ResourceManager.GetString("SpeedUnitKt", resourceCulture);
            }
        }
    }
}
