//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aran.PANDA.RNAV.Departure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aran.PANDA.RNAV.Departure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HIDE_INFO {
            get {
                object obj = ResourceManager.GetObject("HIDE_INFO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SHOW_INFO {
            get {
                object obj = ResourceManager.GetObject("SHOW_INFO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string str00000 {
            get {
                return ResourceManager.GetString("str00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string str00001 {
            get {
                return ResourceManager.GetString("str00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string str00002 {
            get {
                return ResourceManager.GetString("str00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string str00003 {
            get {
                return ResourceManager.GetString("str00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string str00004 {
            get {
                return ResourceManager.GetString("str00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string str00005 {
            get {
                return ResourceManager.GetString("str00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string str00006 {
            get {
                return ResourceManager.GetString("str00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string str00007 {
            get {
                return ResourceManager.GetString("str00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string str00008 {
            get {
                return ResourceManager.GetString("str00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string str00020 {
            get {
                return ResourceManager.GetString("str00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NM.
        /// </summary>
        internal static string str00021 {
            get {
                return ResourceManager.GetString("str00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meter.
        /// </summary>
        internal static string str00022 {
            get {
                return ResourceManager.GetString("str00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feet.
        /// </summary>
        internal static string str00023 {
            get {
                return ResourceManager.GetString("str00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kM/h.
        /// </summary>
        internal static string str00024 {
            get {
                return ResourceManager.GetString("str00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kt.
        /// </summary>
        internal static string str00025 {
            get {
                return ResourceManager.GetString("str00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/min.
        /// </summary>
        internal static string str00026 {
            get {
                return ResourceManager.GetString("str00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feet/min.
        /// </summary>
        internal static string str00027 {
            get {
                return ResourceManager.GetString("str00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNAV Departure.
        /// </summary>
        internal static string str00033 {
            get {
                return ResourceManager.GetString("str00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;PANDA&apos; application is not accessable..
        /// </summary>
        internal static string str00070 {
            get {
                return ResourceManager.GetString("str00070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runway and Obstacles.
        /// </summary>
        internal static string str00300 {
            get {
                return ResourceManager.GetString("str00300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Adjustment.
        /// </summary>
        internal static string str00301 {
            get {
                return ResourceManager.GetString("str00301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment termination.
        /// </summary>
        internal static string str00302 {
            get {
                return ResourceManager.GetString("str00302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure transitions.
        /// </summary>
        internal static string str00303 {
            get {
                return ResourceManager.GetString("str00303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string str00304 {
            get {
                return ResourceManager.GetString("str00304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDG calculation.
        /// </summary>
        internal static string str00400 {
            get {
                return ResourceManager.GetString("str00400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial segment.
        /// </summary>
        internal static string str00410 {
            get {
                return ResourceManager.GetString("str00410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current segment.
        /// </summary>
        internal static string str00420 {
            get {
                return ResourceManager.GetString("str00420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segments.
        /// </summary>
        internal static string str00430 {
            get {
                return ResourceManager.GetString("str00430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual clearances.
        /// </summary>
        internal static string str00440 {
            get {
                return ResourceManager.GetString("str00440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstacles localized in sectors.
        /// </summary>
        internal static string str00450 {
            get {
                return ResourceManager.GetString("str00450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerodrome:.
        /// </summary>
        internal static string str00501 {
            get {
                return ResourceManager.GetString("str00501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure name:.
        /// </summary>
        internal static string str00502 {
            get {
                return ResourceManager.GetString("str00502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runway:.
        /// </summary>
        internal static string str00503 {
            get {
                return ResourceManager.GetString("str00503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft category: up to .
        /// </summary>
        internal static string str00504 {
            get {
                return ResourceManager.GetString("str00504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date:.
        /// </summary>
        internal static string str00505 {
            get {
                return ResourceManager.GetString("str00505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation time:.
        /// </summary>
        internal static string str00506 {
            get {
                return ResourceManager.GetString("str00506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distances are in.
        /// </summary>
        internal static string str00507 {
            get {
                return ResourceManager.GetString("str00507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevations and heights are in.
        /// </summary>
        internal static string str00508 {
            get {
                return ResourceManager.GetString("str00508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeds are in.
        /// </summary>
        internal static string str00509 {
            get {
                return ResourceManager.GetString("str00509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save files....
        /// </summary>
        internal static string str00511 {
            get {
                return ResourceManager.GetString("str00511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial point of the departure procedure..
        /// </summary>
        internal static string str00512 {
            get {
                return ResourceManager.GetString("str00512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy report.
        /// </summary>
        internal static string str00516 {
            get {
                return ResourceManager.GetString("str00516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure geometry.
        /// </summary>
        internal static string str00517 {
            get {
                return ResourceManager.GetString("str00517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The departure procedure overall length.
        /// </summary>
        internal static string str00519 {
            get {
                return ResourceManager.GetString("str00519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file..
        /// </summary>
        internal static string str00520 {
            get {
                return ResourceManager.GetString("str00520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string str00564 {
            get {
                return ResourceManager.GetString("str00564", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string str00565 {
            get {
                return ResourceManager.GetString("str00565", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude of the circle center.
        /// </summary>
        internal static string str00566 {
            get {
                return ResourceManager.GetString("str00566", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude of the circle center.
        /// </summary>
        internal static string str00567 {
            get {
                return ResourceManager.GetString("str00567", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string str00568 {
            get {
                return ResourceManager.GetString("str00568", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string str00569 {
            get {
                return ResourceManager.GetString("str00569", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning radius.
        /// </summary>
        internal static string str00572 {
            get {
                return ResourceManager.GetString("str00572", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn direction.
        /// </summary>
        internal static string str00573 {
            get {
                return ResourceManager.GetString("str00573", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string str00574 {
            get {
                return ResourceManager.GetString("str00574", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string str00575 {
            get {
                return ResourceManager.GetString("str00575", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle of the turn.
        /// </summary>
        internal static string str00576 {
            get {
                return ResourceManager.GetString("str00576", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True course.
        /// </summary>
        internal static string str00577 {
            get {
                return ResourceManager.GetString("str00577", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance to the next point.
        /// </summary>
        internal static string str00578 {
            get {
                return ResourceManager.GetString("str00578", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn arc length.
        /// </summary>
        internal static string str00579 {
            get {
                return ResourceManager.GetString("str00579", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude at FIX:.
        /// </summary>
        internal static string str01501 {
            get {
                return ResourceManager.GetString("str01501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runway direction designator:.
        /// </summary>
        internal static string str02001 {
            get {
                return ResourceManager.GetString("str02001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about obstacles.
        /// </summary>
        internal static string str03002 {
            get {
                return ResourceManager.GetString("str03002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TORA:.
        /// </summary>
        internal static string str03003 {
            get {
                return ResourceManager.GetString("str03003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius of Area 3:.
        /// </summary>
        internal static string str03004 {
            get {
                return ResourceManager.GetString("str03004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing format:.
        /// </summary>
        internal static string str03005 {
            get {
                return ResourceManager.GetString("str03005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runway direction magnetic bearing:.
        /// </summary>
        internal static string str03006 {
            get {
                return ResourceManager.GetString("str03006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number within the radius X:.
        /// </summary>
        internal static string str03007 {
            get {
                return ResourceManager.GetString("str03007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. distance from the center of Area 3:.
        /// </summary>
        internal static string str03008 {
            get {
                return ResourceManager.GetString("str03008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMA reference altitude:.
        /// </summary>
        internal static string str03009 {
            get {
                return ResourceManager.GetString("str03009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC limitation:.
        /// </summary>
        internal static string str03010 {
            get {
                return ResourceManager.GetString("str03010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3485 m (Part I, Sec.3, 3.2.4.2.2).
        /// </summary>
        internal static string str03011 {
            get {
                return ResourceManager.GetString("str03011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 115 m/ PDG (Part I, Sec.3, 3.2.3).
        /// </summary>
        internal static string str03012 {
            get {
                return ResourceManager.GetString("str03012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runway direction true bearing:.
        /// </summary>
        internal static string str03013 {
            get {
                return ResourceManager.GetString("str03013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runway.
        /// </summary>
        internal static string str03014 {
            get {
                return ResourceManager.GetString("str03014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODA:.
        /// </summary>
        internal static string str03015 {
            get {
                return ResourceManager.GetString("str03015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Departure track defined by .
        /// </summary>
        internal static string str03101 {
            get {
                return ResourceManager.GetString("str03101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDG:.
        /// </summary>
        internal static string str03102 {
            get {
                return ResourceManager.GetString("str03102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal OIS gradient plus 0.8% of the distance from the DER:.
        /// </summary>
        internal static string str03103 {
            get {
                return ResourceManager.GetString("str03103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude at which a gradient in excess of 3.3% is no longer required:.
        /// </summary>
        internal static string str03104 {
            get {
                return ResourceManager.GetString("str03104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroute req. altitude:.
        /// </summary>
        internal static string str03105 {
            get {
                return ResourceManager.GetString("str03105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causing obstacle:.
        /// </summary>
        internal static string str03106 {
            get {
                return ResourceManager.GetString("str03106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft category:.
        /// </summary>
        internal static string str03107 {
            get {
                return ResourceManager.GetString("str03107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance at which a gradient in excess of 3.3% is no longer required:.
        /// </summary>
        internal static string str03108 {
            get {
                return ResourceManager.GetString("str03108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned acceleration
        ///altitude:.
        /// </summary>
        internal static string str03109 {
            get {
                return ResourceManager.GetString("str03109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure .
        /// </summary>
        internal static string str03201 {
            get {
                return ResourceManager.GetString("str03201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At altitude/height.
        /// </summary>
        internal static string str03202 {
            get {
                return ResourceManager.GetString("str03202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At WPT.
        /// </summary>
        internal static string str03203 {
            get {
                return ResourceManager.GetString("str03203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned turn more than 15°.
        /// </summary>
        internal static string str03204 {
            get {
                return ResourceManager.GetString("str03204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns before DER are accommodated.
        /// </summary>
        internal static string str03205 {
            get {
                return ResourceManager.GetString("str03205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied PDG:.
        /// </summary>
        internal static string str03206 {
            get {
                return ResourceManager.GetString("str03206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dist. from DER:.
        /// </summary>
        internal static string str03207 {
            get {
                return ResourceManager.GetString("str03207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated field:.
        /// </summary>
        internal static string str03208 {
            get {
                return ResourceManager.GetString("str03208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DER - WPT dist:.
        /// </summary>
        internal static string str03209 {
            get {
                return ResourceManager.GetString("str03209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DER-KK line dist:.
        /// </summary>
        internal static string str03210 {
            get {
                return ResourceManager.GetString("str03210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average track
        ///climp gradient:.
        /// </summary>
        internal static string str03211 {
            get {
                return ResourceManager.GetString("str03211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data on RWY.
        /// </summary>
        internal static string str15056 {
            get {
                return ResourceManager.GetString("str15056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string str15072 {
            get {
                return ResourceManager.GetString("str15072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary Assessment Area.
        /// </summary>
        internal static string str15075 {
            get {
                return ResourceManager.GetString("str15075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight departure.
        /// </summary>
        internal static string str15079 {
            get {
                return ResourceManager.GetString("str15079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string str15080 {
            get {
                return ResourceManager.GetString("str15080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string str15081 {
            get {
                return ResourceManager.GetString("str15081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstacle clearance is calculated for the gradient .
        /// </summary>
        internal static string str15087 {
            get {
                return ResourceManager.GetString("str15087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  % within TA.
        /// </summary>
        internal static string str15088 {
            get {
                return ResourceManager.GetString("str15088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Initiation Area.
        /// </summary>
        internal static string str15090 {
            get {
                return ResourceManager.GetString("str15090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number within the radius of.
        /// </summary>
        internal static string str15261 {
            get {
                return ResourceManager.GetString("str15261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANS OPS.
        /// </summary>
        internal static string str15268 {
            get {
                return ResourceManager.GetString("str15268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNAV departure.
        /// </summary>
        internal static string str15479 {
            get {
                return ResourceManager.GetString("str15479", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about obstacles.
        /// </summary>
        internal static string str30002 {
            get {
                return ResourceManager.GetString("str30002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNAV 1.
        /// </summary>
        internal static string str30201 {
            get {
                return ResourceManager.GetString("str30201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNAV 2.
        /// </summary>
        internal static string str30202 {
            get {
                return ResourceManager.GetString("str30202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNP 1.
        /// </summary>
        internal static string str30203 {
            get {
                return ResourceManager.GetString("str30203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNSS.
        /// </summary>
        internal static string str30204 {
            get {
                return ResourceManager.GetString("str30204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DME-DME.
        /// </summary>
        internal static string str30205 {
            get {
                return ResourceManager.GetString("str30205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOR-DME.
        /// </summary>
        internal static string str30206 {
            get {
                return ResourceManager.GetString("str30206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust manually.
        /// </summary>
        internal static string str31301 {
            get {
                return ResourceManager.GetString("str31301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to the left.
        /// </summary>
        internal static string str31302 {
            get {
                return ResourceManager.GetString("str31302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to the right.
        /// </summary>
        internal static string str31303 {
            get {
                return ResourceManager.GetString("str31303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string str39014 {
            get {
                return ResourceManager.GetString("str39014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string str39015 {
            get {
                return ResourceManager.GetString("str39015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string str40000 {
            get {
                return ResourceManager.GetString("str40000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string str40001 {
            get {
                return ResourceManager.GetString("str40001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string str40002 {
            get {
                return ResourceManager.GetString("str40002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string str40003 {
            get {
                return ResourceManager.GetString("str40003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hor. accuracy.
        /// </summary>
        internal static string str40004 {
            get {
                return ResourceManager.GetString("str40004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height above DER.
        /// </summary>
        internal static string str40005 {
            get {
                return ResourceManager.GetString("str40005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vert. accuracy.
        /// </summary>
        internal static string str40006 {
            get {
                return ResourceManager.GetString("str40006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient to the obstacle top, %.
        /// </summary>
        internal static string str40007 {
            get {
                return ResourceManager.GetString("str40007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC.
        /// </summary>
        internal static string str40008 {
            get {
                return ResourceManager.GetString("str40008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. H.
        /// </summary>
        internal static string str40009 {
            get {
                return ResourceManager.GetString("str40009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req H &gt;60 m.
        /// </summary>
        internal static string str40010 {
            get {
                return ResourceManager.GetString("str40010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. gradient, %.
        /// </summary>
        internal static string str40011 {
            get {
                return ResourceManager.GetString("str40011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDG, %.
        /// </summary>
        internal static string str40012 {
            get {
                return ResourceManager.GetString("str40012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track length of climbing at PDG.
        /// </summary>
        internal static string str40013 {
            get {
                return ResourceManager.GetString("str40013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. height reached using PDG.
        /// </summary>
        internal static string str40014 {
            get {
                return ResourceManager.GetString("str40014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string str40015 {
            get {
                return ResourceManager.GetString("str40015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached H.
        /// </summary>
        internal static string str40016 {
            get {
                return ResourceManager.GetString("str40016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height resulting from PDG.
        /// </summary>
        internal static string str40026 {
            get {
                return ResourceManager.GetString("str40026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H penetration.
        /// </summary>
        internal static string str40027 {
            get {
                return ResourceManager.GetString("str40027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRG. GEO. , °.
        /// </summary>
        internal static string str40028 {
            get {
                return ResourceManager.GetString("str40028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortage,.
        /// </summary>
        internal static string str40029 {
            get {
                return ResourceManager.GetString("str40029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close-In.
        /// </summary>
        internal static string str40030 {
            get {
                return ResourceManager.GetString("str40030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. TNH.
        /// </summary>
        internal static string str40031 {
            get {
                return ResourceManager.GetString("str40031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d0.
        /// </summary>
        internal static string str40032 {
            get {
                return ResourceManager.GetString("str40032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr*.
        /// </summary>
        internal static string str40033 {
            get {
                return ResourceManager.GetString("str40033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC.
        /// </summary>
        internal static string str40034 {
            get {
                return ResourceManager.GetString("str40034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d0Sum,.
        /// </summary>
        internal static string str40035 {
            get {
                return ResourceManager.GetString("str40035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC.
        /// </summary>
        internal static string str40103 {
            get {
                return ResourceManager.GetString("str40103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Req. H.
        /// </summary>
        internal static string str40104 {
            get {
                return ResourceManager.GetString("str40104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report on Obstacles..
        /// </summary>
        internal static string str40105 {
            get {
                return ResourceManager.GetString("str40105", resourceCulture);
            }
        }
    }
}
