using System;

namespace Aran.Aim
{
	internal enum AllAimObjectType
	{
		#region FieldType,
		//****************************   FIELDTYPE  **********************************
		
		_1_FIELDTYPE = 1,
		SysGuid = 2,
		SysDouble = 3,
		SysString = 4,
		SysUInt32 = 5,
		SysInt32 = 6,
		SysInt64 = 7,
		SysBool = 8,
		SysDateTime = 9,
		SysEnum = 10,
		GeoPoint = 128,
		GeoPolyline = 129,
		GeoPolygon = 130,
		
		#endregion,
		
		#region DataType,
		//****************************   DATATYPES  **********************************
		
		//_2_DATATYPE = 512,
		//_2_1_VALCLASS_BEGIN = 513,
		//ValWeight = 514,
		//ValTemperature = 515,
		//ValSpeed = 516,
		//ValPressure = 517,
		//ValLightIntensity = 518,
		//ValFrequency = 519,
		//ValFL = 520,
		//ValDuration = 521,
		//ValDistanceVertical = 522,
		//ValDistanceSigned = 523,
		//ValDistance = 524,
		//ValDepth = 525,
		//_2_1_VALCLASS_END = 526,
		//TimeSlice = 527,
		//TimePeriod = 528,
		//TextNote = 529,
		//Telephone = 530,
		//ResponsibleParty = 531,
		//FeatureRef = 532,
		//DataQualityElement = 533,
		//Contact = 534,
		//Citiation = 535,
		//CIResponsibleParty = 536,
		//CIDate = 537,
		//CIContact = 538,
		//CICitation = 539,
		//CIAddress = 540,
		//_2_2_ABSTRACTCLASS_BEGIN = 541,
		//AbstractTrafficSeparationServiceRef = 542,
		//AbstractSurveillanceRadarRef = 543,
		//AbstractServiceRef = 544,
		//AbstractSegmentLegRef = 545,
		//AbstractRadarEquipmentRef = 546,
		//AbstractProcedureRef = 547,
		//AbstractNavigationSystemCheckpointRef = 548,
		//AbstractNavaidEquipmentRef = 549,
		//AbstractMarkingRef = 550,
		//AbstractGroundLightSystemRef = 551,
		//AbstractApproachLegRef = 552,
		//AbstractAirportHeliportProtectionAreaRef = 553,
		//AbstractAirportGroundServiceRef = 554,
		//_2_2_ABSTRACTCLASS_END = 555,

		_2_DATATYPE = 512,
		_2_1_VALCLASS_BEGIN = 513,
		ValWeight = 514,
		ValTemperature = 515,
		ValSpeed = 516,
		ValPressure = 517,
		ValLightIntensity = 518,
		ValFrequency = 519,
		ValFL = 520,
		ValDuration = 521,
		ValDistanceVertical = 522,
		ValDistanceSigned = 523,
		ValDistance = 524,
		ValDepth = 525,
		_2_1_VALCLASS_END = 526,
		TimeSlice = 527,
		TimePeriod = 528,
		TextNote = 529,
		FeatureRef = 530,
		_2_2_ABSTRACTCLASS_BEGIN = 531,
		AbstractTrafficSeparationServiceRef = 532,
		AbstractSurveillanceRadarRef = 533,
		AbstractServiceRef = 534,
		AbstractSegmentLegRef = 535,
		AbstractRadarEquipmentRef = 536,
		AbstractProcedureRef = 537,
		AbstractNavigationSystemCheckpointRef = 538,
		AbstractNavaidEquipmentRef = 539,
		AbstractMarkingRef = 540,
		AbstractGroundLightSystemRef = 541,
		AbstractApproachLegRef = 542,
		AbstractAirportHeliportProtectionAreaRef = 543,
		AbstractAirportGroundServiceRef = 544,
		_2_2_ABSTRACTCLASS_END = 545,

		_2_3_METADATA_BEGIN = 600,
		Telephone = 601,
		ResponsibleParty = 602,
		DataQualityElement = 603,
		Contact = 604,
		Citiation = 605,
		CIResponsibleParty = 606,
		CIDate = 607,
		CIContact = 608,
		CICitation = 609,
		CIAddress = 610,
		_2_3_METADATA_END = 611,

		#endregion,
		
		#region Object,
		//****************************   OBJECTS  **********************************

		_3_OBJECT = 1021,
		PointExtension = 1022,
		SurfaceExtension = 1023,
		CurveExtension = 1024,
		ArrestingGearExtent = 1025,
		NavaidEquipmentDistance = 1026,
		RunwayDeclaredDistance = 1027,
		RunwayDeclaredDistanceValue = 1028,
		ManoeuvringAreaAvailability = 1029,
		ManoeuvringAreaUsage = 1030,
		ApronAreaAvailability = 1031,
		ApronAreaUsage = 1032,
		LightActivation = 1033,
		GroundLightingAvailability = 1034,
		MarkingElement = 1035,
		MarkingExtent = 1036,
		Ridge = 1037,
		RunwayContamination = 1038,
		TaxiwayContamination = 1039,
		SurfaceContaminationLayer = 1040,
		RunwaySectionContamination = 1041,
		TouchDownLiftOffContamination = 1042,
		ApronContamination = 1043,
		AircraftStandContamination = 1044,
		AirportHeliportContamination = 1045,
		SurfaceCharacteristics = 1046,
		City = 1047,
		AirportHeliportResponsibilityOrganisation = 1048,
		AltimeterSourceStatus = 1049,
		WorkareaActivity = 1050,
		ConditionCombination = 1051,
		AirportHeliportAvailability = 1052,
		AirportHeliportUsage = 1053,
		AirspaceGeometryComponent = 1054,
		AirspaceVolume = 1055,
		AirspaceActivation = 1056,
		AirspaceLayerClass = 1057,
		AirspaceVolumeDependency = 1058,
		Curve = 1059,
		ElevatedCurve = 1060,
		ElevatedPoint = 1061,
		ElevatedSurface = 1062,
		AixmPoint = 1063,
		Surface = 1064,
		RadarComponent = 1065,
		Reflector = 1066,
		SurveillanceGroundStation = 1067,
		ObstacleAssessmentArea = 1068,
		Obstruction = 1069,
		AltitudeAdjustment = 1070,
		ObstaclePlacement = 1071,
		StandardLevel = 1072,
		EquipmentChoice = 1073,
		ContactInformation = 1074,
		OnlineContact = 1075,
		PostalAddress = 1076,
		TelephoneContact = 1077,
		AircraftCharacteristic = 1078,
		FlightCharacteristic = 1079,
		LightElement = 1080,
		LightElementStatus = 1081,
		AirspaceLayer = 1082,
		CircleSector = 1083,
		Timesheet = 1084,
		Meteorology = 1085,
		CallsignDetail = 1086,
		Fuel = 1087,
		Nitrogen = 1088,
		Oil = 1089,
		Oxygen = 1090,
		ServiceOperationalStatus = 1091,
		RadioCommunicationOperationalStatus = 1092,
		PointReference = 1093,
		TerminalSegmentPoint = 1094,
		EnRouteSegmentPoint = 1095,
		AngleUse = 1096,
		AuthorityForNavaidEquipment = 1097,
		AuthorityForSpecialNavigationStation = 1098,
		AuthorityForSpecialNavigationSystem = 1099,
		NavaidComponent = 1100,
		NavaidOperationalStatus = 1101,
		NavaidEquipmentMonitoring = 1102,
		SpecialNavigationStationStatus = 1103,
		SignificantPoint = 1104,
		GuidanceService = 1105,
		Note = 1106,
		LinguisticNote = 1107,
		OrganisationAuthorityAssociation = 1108,
		UnitDependency = 1109,
		UnitAvailability = 1110,
		VerticalStructurePartGeometry = 1111,
		VerticalStructurePart = 1112,
		ObstacleAreaOrigin = 1113,
		VerticalStructureLightingStatus = 1114,
		CirclingRestriction = 1115,
		Minima = 1116,
		EquipmentUnavailableAdjustment = 1117,
		EquipmentUnavailableAdjustmentColumn = 1118,
		TerminalArrivalAreaSector = 1119,
		FASDataBlock = 1120,
		ApproachAltitudeTable = 1121,
		ApproachDistanceTable = 1122,
		ApproachTimingTable = 1123,
		FinalProfile = 1124,
		MissedApproachGroup = 1125,
		ApproachCondition = 1126,
		NavigationAreaSector = 1127,
		DepartureArrivalCondition = 1128,
		SectorDesign = 1129,
		ProcedureAvailability = 1130,
		ProcedureTransition = 1131,
		HoldingUse = 1132,
		ProcedureTransitionLeg = 1133,
		LandingTakeoffAreaCollection = 1134,
		SafeAltitudeAreaSector = 1135,
		HoldingPatternLength = 1136,
		HoldingPatternDuration = 1137,
		HoldingPatternDistance = 1138,
		DirectFlightSegment = 1139,
		FlightConditionCombination = 1140,
		FlightConditionCircumstance = 1141,
		FlightRestrictionLevel = 1142,
		FlightRestrictionRoute = 1143,
		FlightRoutingElement = 1144,
		FlightConditionElement = 1145,
		FlightConditionElementChoice = 1146,
		FlightRoutingElementChoice = 1147,
		RouteAvailability = 1148,
		RoutePortion = 1149,
		AerialRefuellingPoint = 1150,
		AerialRefuellingAnchor = 1151,
		AerialRefuellingTrack = 1152,
		AuthorityForAerialRefuelling = 1153,
		FeatureRefObject = 1154,
		AbstractGroundLightSystemRefObject = 1155,
		AbstractMarkingRefObject = 1156,
		AbstractAirportHeliportProtectionAreaRefObject = 1157,
		AbstractRadarEquipmentRefObject = 1158,
		AbstractSurveillanceRadarRefObject = 1159,
		AbstractServiceRefObject = 1160,
		AbstractTrafficSeparationServiceRefObject = 1161,
		AbstractAirportGroundServiceRefObject = 1162,
		AbstractNavaidEquipmentRefObject = 1163,
		AbstractNavigationSystemCheckpointRefObject = 1164,
		AbstractProcedureRefObject = 1165,
		AbstractSegmentLegRefObject = 1166,
		AbstractApproachLegRefObject = 1167,

		_3_2_METADATA_BEGIN = 1400,
		
		MDMetadata = 1401,
		MessageMetadata = 1402,
		MDConstraints = 1403,
		IdentificationMessage = 1404,
		MDLegalConstraints = 1405,
		LegalConstraints = 1406,
		MDSecurityConstraints = 1407,
		SecurityConstraints = 1408,
		FeatureMetadata = 1409,
		IdentificationFeature = 1410,
		FeatureTimeSliceMetadata = 1411,
		DataQuality = 1412,
		IdentificationTimesliceFeature = 1413,

		_3_2_METADATA_END = 1414,

        _3_2_ISO_METADATA_BEGIN = 1420,

	    BtString,
	    BtDateTime,
	    BtTimePosition,
	    BtTimePeriod,
	    CiTelephone,
	    CiAddress,
	    CiOnlineResource,
	    CiContact,
	    CiResponsibleParty,
	    MdIdentifier,
	    CiPresentationFormCodeObject,
	    CiSeries,
	    CiCitation,
	    MdConstraintsObject,
        MdRestrictionCodeObject,
	    MdLegalConstraints,
	    MdSecurityConstraints,
	    MdProgressCodeObject,
	    MdAbstractIdentificationObject,
        ExTemporalExtent,
	    ExVerticalExtent,
	    ExExtent,
	    MdDataIdentification,
	    DqAbstractResultObject,
	    DqQuantitativeResult,
	    DqAbstractElementObject,
        DqQuantitativeAttributeAccuracy,
	    RsIdentifier,
	    LiSource,
	    LiProcessStep,
	    LiLineage,
	    DqDataQuality,
	    MdMetadata,

        _3_2_ISO_METADATA_END,
        #endregion,

        #region Feature,
        //****************************   FEATURE  **********************************

        _4_FEATURE = 1536,
		RunwayProtectArea = 1537,
		RunwayDirection = 1538,
		RunwayCentrelinePoint = 1539,
		Runway = 1540,
		ArrestingGear = 1541,
		RunwayElement = 1542,
		VisualGlideSlopeIndicator = 1543,
		RunwayVisualRange = 1544,
		RunwayBlastPad = 1545,
		TaxiHoldingPosition = 1546,
		Taxiway = 1547,
		TaxiwayElement = 1548,
		GuidanceLine = 1549,
		Apron = 1550,
		ApronElement = 1551,
		AircraftStand = 1552,
		Road = 1553,
		DeicingArea = 1554,
		PassengerLoadingBridge = 1555,
		TouchDownLiftOffSafeArea = 1556,
		TouchDownLiftOff = 1557,
		ApronLightSystem = 1558,
		TaxiwayLightSystem = 1559,
		RunwayDirectionLightSystem = 1560,
		TouchDownLiftOffLightSystem = 1561,
		GuidanceLineLightSystem = 1562,
		RunwayProtectAreaLightSystem = 1563,
		TaxiHoldingPositionLightSystem = 1564,
		ApproachLightingSystem = 1565,
		TaxiwayMarking = 1566,
		ApronMarking = 1567,
		AirportProtectionAreaMarking = 1568,
		TouchDownLiftOffMarking = 1569,
		RunwayMarking = 1570,
		GuidanceLineMarking = 1571,
		DeicingAreaMarking = 1572,
		TaxiHoldingPositionMarking = 1573,
		StandMarking = 1574,
		FloatingDockSite = 1575,
		MarkingBuoy = 1576,
		SeaplaneLandingArea = 1577,
		SeaplaneRampSite = 1578,
		WorkArea = 1579,
		SurveyControlPoint = 1580,
		NonMovementArea = 1581,
		AirportHeliportCollocation = 1582,
		AirportHeliport = 1583,
		AltimeterSource = 1584,
		AirportHotSpot = 1585,
		AuthorityForAirspace = 1586,
		Airspace = 1587,
		GeoBorder = 1588,
		PrecisionApproachRadar = 1589,
		PrimarySurveillanceRadar = 1590,
		RadarSystem = 1591,
		SecondarySurveillanceRadar = 1592,
		HoldingAssessment = 1593,
		StandardLevelTable = 1594,
		StandardLevelSector = 1595,
		StandardLevelColumn = 1596,
		RadioFrequencyArea = 1597,
		SpecialDate = 1598,
		RadioCommunicationChannel = 1599,
		PilotControlledLighting = 1600,
		InformationService = 1601,
		GroundTrafficControlService = 1602,
		AirTrafficControlService = 1603,
		AirTrafficManagementService = 1604,
		SearchRescueService = 1605,
		PassengerService = 1606,
		AircraftGroundService = 1607,
		FireFightingService = 1608,
		AirportClearanceService = 1609,
		AirportSuppliesService = 1610,
		AngleIndication = 1611,
		DistanceIndication = 1612,
		Azimuth = 1613,
		CheckpointINS = 1614,
		CheckpointVOR = 1615,
		DME = 1616,
		Elevation = 1617,
		Glidepath = 1618,
		Localizer = 1619,
		MarkerBeacon = 1620,
		Navaid = 1621,
		SDF = 1622,
		NDB = 1623,
		SpecialNavigationStation = 1624,
		VOR = 1625,
		TACAN = 1626,
		SpecialNavigationSystem = 1627,
		DirectionFinder = 1628,
		DesignatedPoint = 1629,
		SignificantPointInAirspace = 1630,
		AeronauticalGroundLight = 1631,
		OrganisationAuthority = 1632,
		Unit = 1633,
		ObstacleArea = 1634,
		VerticalStructure = 1635,
		CirclingArea = 1636,
		TerminalArrivalArea = 1637,
		InstrumentApproachProcedure = 1638,
		StandardInstrumentDeparture = 1639,
		NavigationArea = 1640,
		StandardInstrumentArrival = 1641,
		NavigationAreaRestriction = 1642,
		ArrivalFeederLeg = 1643,
		ArrivalLeg = 1644,
		DepartureLeg = 1645,
		FinalLeg = 1646,
		InitialLeg = 1647,
		IntermediateLeg = 1648,
		MissedApproachLeg = 1649,
		ProcedureDME = 1650,
		SafeAltitudeArea = 1651,
		HoldingPattern = 1652,
		UnplannedHolding = 1653,
		AirspaceBorderCrossing = 1654,
		FlightRestriction = 1655,
		RouteSegment = 1656,
		RouteDME = 1657,
		Route = 1658,
		ChangeOverPoint = 1659,
		AerialRefuelling = 1660,
		RulesProcedures = 1661,
		#endregion,
		
		#region Abstract,
		//****************************   ABSTRACT  **********************************
		
		_5_ABSTRACT = 2048,
		SurfaceContamination = 2049,
		UsageCondition = 2050,
		PropertiesWithSchedule = 2051,
		SegmentPoint = 2052,
		DirectFlight = 2053,
		MDIdentification = 2054,
	    BtAbstractObject = 2055,
	    BtAbstractTimePrimitive = 2056,
	    MdConstraints = 2057,
	    MdAbstractIdentification = 2058,
	    DqAbstractResult = 2059,
	    DqAbstractElement = 2060,
        _5_1_ABSTRACT_FEATURE = 2304,
		GroundLightSystem = 2305,
		Marking = 2306,
		AirportHeliportProtectionArea = 2307,
		RadarEquipment = 2308,
		SurveillanceRadar = 2309,
		Service = 2310,
		TrafficSeparationService = 2311,
		AirportGroundService = 2312,
		NavaidEquipment = 2313,
		NavigationSystemCheckpoint = 2314,
		Procedure = 2315,
		SegmentLeg = 2316,
		ApproachLeg = 2317,
		#endregion,
		
		#region Enum,
		//****************************   ENUMS  **********************************
		
		_6_ENUM = 2560,
		CIRoleCode = 2561,
		CIDateTypeCode = 2562,
		DQEvaluationMethodTypeCode = 2563,
		MDProgressCode = 2564,
		UomFL = 2565,
		UomDistance = 2566,
		UomDistanceVertical = 2567,
		UomDuration = 2568,
		UomFrequency = 2569,
		UomPressure = 2570,
		UomSpeed = 2571,
		UomTemperature = 2572,
		UomWeight = 2573,
		UomDepth = 2574,
		UomLightIntensity = 2575,
		CodeAircraftEngineNumber = 2576,
		CodeAirspaceActivity = 2577,
		CodeAircraftCategory = 2578,
		CodeFireFighting = 2579,
		CodeFuel = 2580,
		CodeOil = 2581,
		CodeDMEChannel = 2582,
		CodeMLSChannel = 2583,
		CodeTACANChannel = 2584,
		CodeHelicopterPerformance = 2585,
		CodeMarkerBeaconSignal = 2586,
		CodeNDBUsage = 2587,
		CodeColour = 2588,
		CodeTimeEventCombination = 2589,
		CodeComparison = 2590,
		CodeSurfaceComposition = 2591,
		CodeSurfaceCondition = 2592,
		CodeDay = 2593,
		CodeAltitudeUse = 2594,
		CodeDirection = 2595,
		CodeDirectionReference = 2596,
		CodeDirectionTurn = 2597,
		CodeVerticalReference = 2598,
		CodeRadioEmission = 2599,
		CodeFlowConditionOperation = 2600,
		CodeFlightStatus = 2601,
		CodeFlight = 2602,
		CodeProcedureFixRole = 2603,
		CodeLevelTableDesignator = 2604,
		CodeRouteOrigin = 2605,
		CodeLightIntensity = 2606,
		CodeAviationStandards = 2607,
		CodeLevel = 2608,
		CodeMilitaryStatus = 2609,
		CodeAirspaceAggregation = 2610,
		CodeFlightOrigin = 2611,
		CodePCNMethod = 2612,
		CodePCNTyrePressure = 2613,
		CodePCNSubgrade = 2614,
		CodePCNPavement = 2615,
		CodeProcedurePhase = 2616,
		CodeSurfacePreparation = 2617,
		CodeApronSection = 2618,
		CodePositionInILS = 2619,
		CodeSide = 2620,
		CodeRunwaySection = 2621,
		CodeTLOFSection = 2622,
		CodeTaxiwaySection = 2623,
		CodeFlightPurpose = 2624,
		CodeLocationQualifier = 2625,
		CodeATCReporting = 2626,
		CodeRouteAvailability = 2627,
		CodeRVSMPointRole = 2628,
		CodeSpecialDate = 2629,
		CodeSpeedReference = 2630,
		CodeTimeEvent = 2631,
		CodeTimeReference = 2632,
		CodeAircraft = 2633,
		CodeAircraftEngine = 2634,
		CodeAirportHeliport = 2635,
		CodeAirportHeliportCollocation = 2636,
		CodeGroundLighting = 2637,
		CodeApproachLighting = 2638,
		CodeBearing = 2639,
		CodeAirspace = 2640,
		CodeAuthority = 2641,
		CodeAirspacePointRole = 2642,
		CodeOrganisationHierarchy = 2643,
		CodeMLSAzimuth = 2644,
		CodeCourse = 2645,
		CodeDeclaredDistance = 2646,
		CodeDesignatedPoint = 2647,
		CodeDME = 2648,
		CodeFlightRule = 2649,
		CodeGeoBorder = 2650,
		CodeHoldingUsage = 2651,
		CodeLightSource = 2652,
		CodeMilitaryOperations = 2653,
		CodeRadioFrequencyArea = 2654,
		CodeNitrogen = 2655,
		CodeNorthReference = 2656,
		CodeOrganisation = 2657,
		CodeOxygen = 2658,
		CodeSegmentPath = 2659,
		CodeRunwayProtectionArea = 2660,
		CodeFlightRestriction = 2661,
		CodeRouteNavigation = 2662,
		CodeRouteSegmentPath = 2663,
		CodeAircraftGroundService = 2664,
		CodeSpecialNavigationStation = 2665,
		CodeSpecialNavigationSystem = 2666,
		CodeAircraftStand = 2667,
		CodeTaxiway = 2668,
		CodeUnit = 2669,
		CodeILSBackCourse = 2670,
		CodeVASIS = 2671,
		CodeUsageLimitation = 2672,
		CodeStatusConstruction = 2673,
		CodeStatusOperations = 2674,
		CodeVerticalStructure = 2675,
		CodeVerticalStructureMarking = 2676,
		CodeCardinalDirection = 2677,
		CodeFreeFlight = 2678,
		CodeNavaidService = 2679,
		CodeVerticalDatum = 2680,
		CodeRouteDesignatorPrefix = 2681,
		CodeRVSM = 2682,
		CodeRouteDesignatorLetter = 2683,
		CodeRouteDesignatorSuffix = 2684,
		CodeStatusAirspace = 2685,
		CodeRunwayPointRole = 2686,
		CodeRunway = 2687,
		CodeMarkingStyle = 2688,
		CodeFinalGuidance = 2689,
		CodeMissedApproach = 2690,
		CodeUpperAlpha = 2691,
		CodeApproachPrefix = 2692,
		CodeApproach = 2693,
		CodeApproval = 2694,
		CodeDesignStandard = 2695,
		CodeApproachEquipmentAdditional = 2696,
		CodeEquipmentUnavailable = 2697,
		CodeHoldingUse = 2698,
		CodeProcedureDistance = 2699,
		CodeMinimaFinalApproachPath = 2700,
		CodeMinimumAltitude = 2701,
		CodeMinimumHeight = 2702,
		CodeProcedureCodingStandard = 2703,
		CodeSafeAltitude = 2704,
		CodeObstacleAssessmentSurface = 2705,
		CodeAltitudeAdjustment = 2706,
		CodeTAA = 2707,
		CodeArcDirection = 2708,
		CodeLevelSeries = 2709,
		CodeSegmentTermination = 2710,
		CodeReferenceRole = 2711,
		CodeTrajectory = 2712,
		CodeRunwayMarking = 2713,
		CodeRVRReading = 2714,
		CodeStatusNavaid = 2715,
		CodeOperationAirportHeliport = 2716,
		CodeDistanceIndication = 2717,
		CodeObstacleArea = 2718,
		CodeAirspaceClassification = 2719,
		CodeApronElement = 2720,
		CodeRunwayElement = 2721,
		CodeAuthorityRole = 2722,
		CodeVOR = 2723,
		CodeApproachLightingICAO = 2724,
		CodeLightingJAR = 2725,
		CodeWorkArea = 2726,
		CodeVerticalStructureMaterial = 2727,
		CodeGuidanceLine = 2728,
		CodeAirportWarning = 2729,
		CodeProtectAreaSection = 2730,
		CodeRoute = 2731,
		CodeAirspacePointPosition = 2732,
		CodeContamination = 2733,
		CodeFrictionDevice = 2734,
		CodeFrictionEstimate = 2735,
		CodeHeightReference = 2736,
		CodeAerialRefuellingPoint = 2737,
		CodeAerialRefuelling = 2738,
		CodeLoadingBridge = 2739,
		CodeApproachGuidance = 2740,
		CodeAircraftWingspanClass = 2741,
		CodeArrestingGearEngageDevice = 2742,
		CodeObstructionIdSurfaceZone = 2743,
		CodeBuoy = 2744,
		CodeRoad = 2745,
		CodeAerialRefuellingPrefix = 2746,
		CodeMilitaryTraining = 2747,
		CodeFacilityRanking = 2748,
		CodeMilitaryRoutePoint = 2749,
		CodeArrestingGearEnergyAbsorb = 2750,
		CodeEmissionBand = 2751,
		CodeMeteoConditions = 2752,
		CodeValueInterpretation = 2753,
		CodeNavigationArea = 2754,
		CodeProcedureAvailability = 2755,
		CodePilotControlledLighting = 2756,
		CodeIntensityStandBy = 2757,
		CodeTelecomNetwork = 2758,
		CodeFlightDestination = 2759,
		CodeServiceInformation = 2760,
		CodeServiceATFM = 2761,
		CodeServiceATC = 2762,
		CodeServiceSAR = 2763,
		CodeCommunicationChannel = 2764,
		CodePassengerService = 2765,
		CodeServiceGroundControl = 2766,
		CodeStatusService = 2767,
		CodeCommunicationMode = 2768,
		CodeCommunicationDirection = 2769,
		CodeCheckpointCategory = 2770,
		CodeLightHoldingPosition = 2771,
		CodeNavigationAreaRestriction = 2772,
		CodeSystemActivation = 2773,
		CodeWakeTurbulence = 2774,
		CodePAR = 2775,
		CodePrimaryRadar = 2776,
		CodeRadarService = 2777,
		CodeReflector = 2778,
		CodeStandbyPower = 2779,
		CodeTransponder = 2780,
		CodeAirspaceDependency = 2781,
		CodeUnitDependency = 2782,
		CodeVisualDockingGuidance = 2783,
		CodeMarkingCondition = 2784,
		CodeNavaidPurpose = 2785,
		CodeRuleProcedure = 2786,
		CodeRuleProcedureTitle = 2787,
		CodeGradeSeparation = 2788,
		CodeTaxiwayElement = 2789,
		CodeRadioSignal = 2790,
		CodeSignalPerformanceILS = 2791,
		CodeCourseQualityILS = 2792,
		CodeIntegrityLevelILS = 2793,
		CodeHoldingCategory = 2794,
		CodeNotePurpose = 2795,
		CodeNavigationEquipment = 2796,
		CodeNavigationSpecification = 2797,
		CodeEquipmentAntiCollision = 2798,
		CodeLogicalOperator = 2799,
		CodeStatusAirport = 2800,
		CodeOperationManoeuvringArea = 2801,
		CodeRelativePosition = 2802,
		TimeSliceInterpretationType = 2803,
		PhoneCodeType = 2804,
		LanguageCodeType = 2805,
		RestrictionCode = 2806,
		ClassificationCode = 2807,
		MeasureClassCode = 2808,
		Language = 2809,
		GroundLightSystemType = 2810,
		MarkingType = 2811,
		AirportHeliportProtectionAreaType = 2812,
		RadarEquipmentType = 2813,
		SurveillanceRadarType = 2814,
		ServiceType = 2815,
		TrafficSeparationServiceType = 2816,
		AirportGroundServiceType = 2817,
		NavaidEquipmentType = 2818,
		NavigationSystemCheckpointType = 2819,
		ProcedureType = 2820,
		SegmentLegType = 2821,
		ApproachLegType = 2822,

        #region ISO METADATA ENUMS

        MdOnLineFunctionCode = 2823,
	    CiDateTypeCode = 2824,
	    CiRoleCode = 2825,
	    CiPresentationFormCode = 2826,
	    MdTimeIndeterminateValueType = 2827,
	    DqEvaluationMethodTypeCode = 2828,
	    MdRestrictionCode = 2829,
	    MdClassificationCode = 2830,
	    MdProgressCode = 2831,

        #endregion

        #endregion
    }
	
	public enum DataType
	{
		ValWeight = AllAimObjectType.ValWeight,
		ValTemperature = AllAimObjectType.ValTemperature,
		ValSpeed = AllAimObjectType.ValSpeed,
		ValPressure = AllAimObjectType.ValPressure,
		ValLightIntensity = AllAimObjectType.ValLightIntensity,
		ValFrequency = AllAimObjectType.ValFrequency,
		ValFL = AllAimObjectType.ValFL,
		ValDuration = AllAimObjectType.ValDuration,
		ValDistanceVertical = AllAimObjectType.ValDistanceVertical,
		ValDistanceSigned = AllAimObjectType.ValDistanceSigned,
		ValDistance = AllAimObjectType.ValDistance,
		ValDepth = AllAimObjectType.ValDepth,
		TimeSlice = AllAimObjectType.TimeSlice,
		TimePeriod = AllAimObjectType.TimePeriod,
		TextNote = AllAimObjectType.TextNote,
		Telephone = AllAimObjectType.Telephone,
		ResponsibleParty = AllAimObjectType.ResponsibleParty,
		FeatureRef = AllAimObjectType.FeatureRef,
		DataQualityElement = AllAimObjectType.DataQualityElement,
		Contact = AllAimObjectType.Contact,
		Citiation = AllAimObjectType.Citiation,
		CIResponsibleParty = AllAimObjectType.CIResponsibleParty,
		CIDate = AllAimObjectType.CIDate,
		CIContact = AllAimObjectType.CIContact,
		CICitation = AllAimObjectType.CICitation,
		CIAddress = AllAimObjectType.CIAddress,
		AbstractTrafficSeparationServiceRef = AllAimObjectType.AbstractTrafficSeparationServiceRef,
		AbstractSurveillanceRadarRef = AllAimObjectType.AbstractSurveillanceRadarRef,
		AbstractServiceRef = AllAimObjectType.AbstractServiceRef,
		AbstractSegmentLegRef = AllAimObjectType.AbstractSegmentLegRef,
		AbstractRadarEquipmentRef = AllAimObjectType.AbstractRadarEquipmentRef,
		AbstractProcedureRef = AllAimObjectType.AbstractProcedureRef,
		AbstractNavigationSystemCheckpointRef = AllAimObjectType.AbstractNavigationSystemCheckpointRef,
		AbstractNavaidEquipmentRef = AllAimObjectType.AbstractNavaidEquipmentRef,
		AbstractMarkingRef = AllAimObjectType.AbstractMarkingRef,
		AbstractGroundLightSystemRef = AllAimObjectType.AbstractGroundLightSystemRef,
		AbstractApproachLegRef = AllAimObjectType.AbstractApproachLegRef,
		AbstractAirportHeliportProtectionAreaRef = AllAimObjectType.AbstractAirportHeliportProtectionAreaRef,
		AbstractAirportGroundServiceRef = AllAimObjectType.AbstractAirportGroundServiceRef
	}
	
	public enum ObjectType
	{
		PointExtension = AllAimObjectType.PointExtension,
		SurfaceExtension = AllAimObjectType.SurfaceExtension,
		CurveExtension = AllAimObjectType.CurveExtension,
		NavaidEquipmentDistance = AllAimObjectType.NavaidEquipmentDistance,
		RunwayDeclaredDistance = AllAimObjectType.RunwayDeclaredDistance,
		RunwayDeclaredDistanceValue = AllAimObjectType.RunwayDeclaredDistanceValue,
		ManoeuvringAreaAvailability = AllAimObjectType.ManoeuvringAreaAvailability,
		ManoeuvringAreaUsage = AllAimObjectType.ManoeuvringAreaUsage,
		ApronAreaAvailability = AllAimObjectType.ApronAreaAvailability,
		ApronAreaUsage = AllAimObjectType.ApronAreaUsage,
		LightActivation = AllAimObjectType.LightActivation,
		GroundLightingAvailability = AllAimObjectType.GroundLightingAvailability,
		MarkingElement = AllAimObjectType.MarkingElement,
		Ridge = AllAimObjectType.Ridge,
		RunwayContamination = AllAimObjectType.RunwayContamination,
		TaxiwayContamination = AllAimObjectType.TaxiwayContamination,
		SurfaceContaminationLayer = AllAimObjectType.SurfaceContaminationLayer,
		RunwaySectionContamination = AllAimObjectType.RunwaySectionContamination,
		TouchDownLiftOffContamination = AllAimObjectType.TouchDownLiftOffContamination,
		ApronContamination = AllAimObjectType.ApronContamination,
		AircraftStandContamination = AllAimObjectType.AircraftStandContamination,
		AirportHeliportContamination = AllAimObjectType.AirportHeliportContamination,
		SurfaceCharacteristics = AllAimObjectType.SurfaceCharacteristics,
		City = AllAimObjectType.City,
		AirportHeliportResponsibilityOrganisation = AllAimObjectType.AirportHeliportResponsibilityOrganisation,
		AltimeterSourceStatus = AllAimObjectType.AltimeterSourceStatus,
		WorkareaActivity = AllAimObjectType.WorkareaActivity,
		ConditionCombination = AllAimObjectType.ConditionCombination,
		AirportHeliportAvailability = AllAimObjectType.AirportHeliportAvailability,
		AirportHeliportUsage = AllAimObjectType.AirportHeliportUsage,
		AirspaceGeometryComponent = AllAimObjectType.AirspaceGeometryComponent,
		AirspaceVolume = AllAimObjectType.AirspaceVolume,
		AirspaceActivation = AllAimObjectType.AirspaceActivation,
		AirspaceLayerClass = AllAimObjectType.AirspaceLayerClass,
		AirspaceVolumeDependency = AllAimObjectType.AirspaceVolumeDependency,
		Curve = AllAimObjectType.Curve,
		ElevatedCurve = AllAimObjectType.ElevatedCurve,
		ElevatedPoint = AllAimObjectType.ElevatedPoint,
		ElevatedSurface = AllAimObjectType.ElevatedSurface,
		AixmPoint = AllAimObjectType.AixmPoint,
		Surface = AllAimObjectType.Surface,
		RadarComponent = AllAimObjectType.RadarComponent,
		Reflector = AllAimObjectType.Reflector,
		SurveillanceGroundStation = AllAimObjectType.SurveillanceGroundStation,
		ObstacleAssessmentArea = AllAimObjectType.ObstacleAssessmentArea,
		Obstruction = AllAimObjectType.Obstruction,
		AltitudeAdjustment = AllAimObjectType.AltitudeAdjustment,
		ObstaclePlacement = AllAimObjectType.ObstaclePlacement,
		StandardLevel = AllAimObjectType.StandardLevel,
		ContactInformation = AllAimObjectType.ContactInformation,
		OnlineContact = AllAimObjectType.OnlineContact,
		PostalAddress = AllAimObjectType.PostalAddress,
		TelephoneContact = AllAimObjectType.TelephoneContact,
		AircraftCharacteristic = AllAimObjectType.AircraftCharacteristic,
		FlightCharacteristic = AllAimObjectType.FlightCharacteristic,
		LightElement = AllAimObjectType.LightElement,
		LightElementStatus = AllAimObjectType.LightElementStatus,
		AirspaceLayer = AllAimObjectType.AirspaceLayer,
		CircleSector = AllAimObjectType.CircleSector,
		Timesheet = AllAimObjectType.Timesheet,
		Meteorology = AllAimObjectType.Meteorology,
		CallsignDetail = AllAimObjectType.CallsignDetail,
		Fuel = AllAimObjectType.Fuel,
		Nitrogen = AllAimObjectType.Nitrogen,
		Oil = AllAimObjectType.Oil,
		Oxygen = AllAimObjectType.Oxygen,
		ServiceOperationalStatus = AllAimObjectType.ServiceOperationalStatus,
		RadioCommunicationOperationalStatus = AllAimObjectType.RadioCommunicationOperationalStatus,
		PointReference = AllAimObjectType.PointReference,
		TerminalSegmentPoint = AllAimObjectType.TerminalSegmentPoint,
		EnRouteSegmentPoint = AllAimObjectType.EnRouteSegmentPoint,
		AngleUse = AllAimObjectType.AngleUse,
		AuthorityForNavaidEquipment = AllAimObjectType.AuthorityForNavaidEquipment,
		AuthorityForSpecialNavigationStation = AllAimObjectType.AuthorityForSpecialNavigationStation,
		AuthorityForSpecialNavigationSystem = AllAimObjectType.AuthorityForSpecialNavigationSystem,
		NavaidComponent = AllAimObjectType.NavaidComponent,
		NavaidOperationalStatus = AllAimObjectType.NavaidOperationalStatus,
		NavaidEquipmentMonitoring = AllAimObjectType.NavaidEquipmentMonitoring,
		SpecialNavigationStationStatus = AllAimObjectType.SpecialNavigationStationStatus,
		Note = AllAimObjectType.Note,
		LinguisticNote = AllAimObjectType.LinguisticNote,
		OrganisationAuthorityAssociation = AllAimObjectType.OrganisationAuthorityAssociation,
		UnitDependency = AllAimObjectType.UnitDependency,
		UnitAvailability = AllAimObjectType.UnitAvailability,
		VerticalStructurePart = AllAimObjectType.VerticalStructurePart,
		VerticalStructureLightingStatus = AllAimObjectType.VerticalStructureLightingStatus,
		CirclingRestriction = AllAimObjectType.CirclingRestriction,
		Minima = AllAimObjectType.Minima,
		EquipmentUnavailableAdjustment = AllAimObjectType.EquipmentUnavailableAdjustment,
		EquipmentUnavailableAdjustmentColumn = AllAimObjectType.EquipmentUnavailableAdjustmentColumn,
		TerminalArrivalAreaSector = AllAimObjectType.TerminalArrivalAreaSector,
		FASDataBlock = AllAimObjectType.FASDataBlock,
		ApproachAltitudeTable = AllAimObjectType.ApproachAltitudeTable,
		ApproachDistanceTable = AllAimObjectType.ApproachDistanceTable,
		ApproachTimingTable = AllAimObjectType.ApproachTimingTable,
		FinalProfile = AllAimObjectType.FinalProfile,
		MissedApproachGroup = AllAimObjectType.MissedApproachGroup,
		ApproachCondition = AllAimObjectType.ApproachCondition,
		NavigationAreaSector = AllAimObjectType.NavigationAreaSector,
		DepartureArrivalCondition = AllAimObjectType.DepartureArrivalCondition,
		SectorDesign = AllAimObjectType.SectorDesign,
		ProcedureAvailability = AllAimObjectType.ProcedureAvailability,
		ProcedureTransition = AllAimObjectType.ProcedureTransition,
		HoldingUse = AllAimObjectType.HoldingUse,
		ProcedureTransitionLeg = AllAimObjectType.ProcedureTransitionLeg,
		LandingTakeoffAreaCollection = AllAimObjectType.LandingTakeoffAreaCollection,
		SafeAltitudeAreaSector = AllAimObjectType.SafeAltitudeAreaSector,
		HoldingPatternDuration = AllAimObjectType.HoldingPatternDuration,
		HoldingPatternDistance = AllAimObjectType.HoldingPatternDistance,
		DirectFlightSegment = AllAimObjectType.DirectFlightSegment,
		FlightConditionCombination = AllAimObjectType.FlightConditionCombination,
		FlightConditionCircumstance = AllAimObjectType.FlightConditionCircumstance,
		FlightRestrictionLevel = AllAimObjectType.FlightRestrictionLevel,
		FlightRestrictionRoute = AllAimObjectType.FlightRestrictionRoute,
		FlightRoutingElement = AllAimObjectType.FlightRoutingElement,
		FlightConditionElement = AllAimObjectType.FlightConditionElement,
		RouteAvailability = AllAimObjectType.RouteAvailability,
		RoutePortion = AllAimObjectType.RoutePortion,
		AerialRefuellingPoint = AllAimObjectType.AerialRefuellingPoint,
		AerialRefuellingAnchor = AllAimObjectType.AerialRefuellingAnchor,
		AerialRefuellingTrack = AllAimObjectType.AerialRefuellingTrack,
		AuthorityForAerialRefuelling = AllAimObjectType.AuthorityForAerialRefuelling,
		MDMetadata = AllAimObjectType.MDMetadata,
		MessageMetadata = AllAimObjectType.MessageMetadata,
		MDConstraints = AllAimObjectType.MDConstraints,
		IdentificationMessage = AllAimObjectType.IdentificationMessage,
		MDLegalConstraints = AllAimObjectType.MDLegalConstraints,
		LegalConstraints = AllAimObjectType.LegalConstraints,
		MDSecurityConstraints = AllAimObjectType.MDSecurityConstraints,
		SecurityConstraints = AllAimObjectType.SecurityConstraints,
		FeatureMetadata = AllAimObjectType.FeatureMetadata,
		IdentificationFeature = AllAimObjectType.IdentificationFeature,
		FeatureTimeSliceMetadata = AllAimObjectType.FeatureTimeSliceMetadata,
		DataQuality = AllAimObjectType.DataQuality,
		IdentificationTimesliceFeature = AllAimObjectType.IdentificationTimesliceFeature,
		FeatureRefObject = AllAimObjectType.FeatureRefObject,
		AbstractGroundLightSystemRefObject = AllAimObjectType.AbstractGroundLightSystemRefObject,
		AbstractMarkingRefObject = AllAimObjectType.AbstractMarkingRefObject,
		AbstractAirportHeliportProtectionAreaRefObject = AllAimObjectType.AbstractAirportHeliportProtectionAreaRefObject,
		AbstractRadarEquipmentRefObject = AllAimObjectType.AbstractRadarEquipmentRefObject,
		AbstractSurveillanceRadarRefObject = AllAimObjectType.AbstractSurveillanceRadarRefObject,
		AbstractServiceRefObject = AllAimObjectType.AbstractServiceRefObject,
		AbstractTrafficSeparationServiceRefObject = AllAimObjectType.AbstractTrafficSeparationServiceRefObject,
		AbstractAirportGroundServiceRefObject = AllAimObjectType.AbstractAirportGroundServiceRefObject,
		AbstractNavaidEquipmentRefObject = AllAimObjectType.AbstractNavaidEquipmentRefObject,
		AbstractNavigationSystemCheckpointRefObject = AllAimObjectType.AbstractNavigationSystemCheckpointRefObject,
		AbstractProcedureRefObject = AllAimObjectType.AbstractProcedureRefObject,
		AbstractSegmentLegRefObject = AllAimObjectType.AbstractSegmentLegRefObject,
		AbstractApproachLegRefObject = AllAimObjectType.AbstractApproachLegRefObject,
		ArrestingGearExtent = AllAimObjectType.ArrestingGearExtent,
		MarkingExtent = AllAimObjectType.MarkingExtent,
		EquipmentChoice = AllAimObjectType.EquipmentChoice,
		SignificantPoint = AllAimObjectType.SignificantPoint,
		GuidanceService = AllAimObjectType.GuidanceService,
		VerticalStructurePartGeometry = AllAimObjectType.VerticalStructurePartGeometry,
		ObstacleAreaOrigin = AllAimObjectType.ObstacleAreaOrigin,
		HoldingPatternLength = AllAimObjectType.HoldingPatternLength,
		FlightConditionElementChoice = AllAimObjectType.FlightConditionElementChoice,
		FlightRoutingElementChoice = AllAimObjectType.FlightRoutingElementChoice,

        #region ISO METADATA OBJECTS

	    BtString = AllAimObjectType.BtString,
	    BtDateTime = AllAimObjectType.BtDateTime,
	    BtTimePosition = AllAimObjectType.BtTimePosition,
	    BtTimePeriod = AllAimObjectType.BtTimePeriod,
	    CiTelephone = AllAimObjectType.CiTelephone,
	    CiAddress = AllAimObjectType.CiAddress,
	    CiOnlineResource = AllAimObjectType.CiOnlineResource,
	    CiContact = AllAimObjectType.CiContact,
	    CiResponsibleParty = AllAimObjectType.CiResponsibleParty,
	    MdIdentifier = AllAimObjectType.MdIdentifier,
	    CiPresentationFormCodeObject = AllAimObjectType.CiPresentationFormCodeObject,
	    CiSeries = AllAimObjectType.CiSeries,
	    CiCitation = AllAimObjectType.CiCitation,
	    MdConstraintsObject = AllAimObjectType.MdConstraintsObject,
	    MdRestrictionCodeObject = AllAimObjectType.MdRestrictionCodeObject,
	    MdLegalConstraints = AllAimObjectType.MdLegalConstraints,
	    MdSecurityConstraints = AllAimObjectType.MdSecurityConstraints,
	    MdProgressCodeObject = AllAimObjectType.MdProgressCodeObject,
	    MdAbstractIdentificationObject = AllAimObjectType.MdAbstractIdentificationObject,
	    ExTemporalExtent = AllAimObjectType.ExTemporalExtent,
	    ExVerticalExtent = AllAimObjectType.ExVerticalExtent,
	    ExExtent = AllAimObjectType.ExExtent,
	    MdDataIdentification = AllAimObjectType.MdDataIdentification,
	    DqAbstractResultObject = AllAimObjectType.DqAbstractResultObject,
	    DqQuantitativeResult = AllAimObjectType.DqQuantitativeResult,
	    DqAbstractElementObject = AllAimObjectType.DqAbstractElementObject,
	    DqQuantitativeAttributeAccuracy = AllAimObjectType.DqQuantitativeAttributeAccuracy,
	    RsIdentifier = AllAimObjectType.RsIdentifier,
	    LiSource = AllAimObjectType.LiSource,
	    LiProcessStep = AllAimObjectType.LiProcessStep,
	    LiLineage = AllAimObjectType.LiLineage,
	    DqDataQuality = AllAimObjectType.DqDataQuality,
	    MdMetadata = AllAimObjectType.MdMetadata

        #endregion
    }
	
	public enum FeatureType
	{
		RunwayProtectArea = AllAimObjectType.RunwayProtectArea,
		RunwayDirection = AllAimObjectType.RunwayDirection,
		RunwayCentrelinePoint = AllAimObjectType.RunwayCentrelinePoint,
		Runway = AllAimObjectType.Runway,
		ArrestingGear = AllAimObjectType.ArrestingGear,
		RunwayElement = AllAimObjectType.RunwayElement,
		VisualGlideSlopeIndicator = AllAimObjectType.VisualGlideSlopeIndicator,
		RunwayVisualRange = AllAimObjectType.RunwayVisualRange,
		RunwayBlastPad = AllAimObjectType.RunwayBlastPad,
		TaxiHoldingPosition = AllAimObjectType.TaxiHoldingPosition,
		Taxiway = AllAimObjectType.Taxiway,
		TaxiwayElement = AllAimObjectType.TaxiwayElement,
		GuidanceLine = AllAimObjectType.GuidanceLine,
		Apron = AllAimObjectType.Apron,
		ApronElement = AllAimObjectType.ApronElement,
		AircraftStand = AllAimObjectType.AircraftStand,
		Road = AllAimObjectType.Road,
		DeicingArea = AllAimObjectType.DeicingArea,
		PassengerLoadingBridge = AllAimObjectType.PassengerLoadingBridge,
		TouchDownLiftOffSafeArea = AllAimObjectType.TouchDownLiftOffSafeArea,
		TouchDownLiftOff = AllAimObjectType.TouchDownLiftOff,
		ApronLightSystem = AllAimObjectType.ApronLightSystem,
		TaxiwayLightSystem = AllAimObjectType.TaxiwayLightSystem,
		RunwayDirectionLightSystem = AllAimObjectType.RunwayDirectionLightSystem,
		TouchDownLiftOffLightSystem = AllAimObjectType.TouchDownLiftOffLightSystem,
		GuidanceLineLightSystem = AllAimObjectType.GuidanceLineLightSystem,
		RunwayProtectAreaLightSystem = AllAimObjectType.RunwayProtectAreaLightSystem,
		TaxiHoldingPositionLightSystem = AllAimObjectType.TaxiHoldingPositionLightSystem,
		ApproachLightingSystem = AllAimObjectType.ApproachLightingSystem,
		TaxiwayMarking = AllAimObjectType.TaxiwayMarking,
		ApronMarking = AllAimObjectType.ApronMarking,
		AirportProtectionAreaMarking = AllAimObjectType.AirportProtectionAreaMarking,
		TouchDownLiftOffMarking = AllAimObjectType.TouchDownLiftOffMarking,
		RunwayMarking = AllAimObjectType.RunwayMarking,
		GuidanceLineMarking = AllAimObjectType.GuidanceLineMarking,
		DeicingAreaMarking = AllAimObjectType.DeicingAreaMarking,
		TaxiHoldingPositionMarking = AllAimObjectType.TaxiHoldingPositionMarking,
		StandMarking = AllAimObjectType.StandMarking,
		FloatingDockSite = AllAimObjectType.FloatingDockSite,
		MarkingBuoy = AllAimObjectType.MarkingBuoy,
		SeaplaneLandingArea = AllAimObjectType.SeaplaneLandingArea,
		SeaplaneRampSite = AllAimObjectType.SeaplaneRampSite,
		WorkArea = AllAimObjectType.WorkArea,
		SurveyControlPoint = AllAimObjectType.SurveyControlPoint,
		NonMovementArea = AllAimObjectType.NonMovementArea,
		AirportHeliportCollocation = AllAimObjectType.AirportHeliportCollocation,
		AirportHeliport = AllAimObjectType.AirportHeliport,
		AltimeterSource = AllAimObjectType.AltimeterSource,
		AirportHotSpot = AllAimObjectType.AirportHotSpot,
		AuthorityForAirspace = AllAimObjectType.AuthorityForAirspace,
		Airspace = AllAimObjectType.Airspace,
		GeoBorder = AllAimObjectType.GeoBorder,
		PrecisionApproachRadar = AllAimObjectType.PrecisionApproachRadar,
		PrimarySurveillanceRadar = AllAimObjectType.PrimarySurveillanceRadar,
		RadarSystem = AllAimObjectType.RadarSystem,
		SecondarySurveillanceRadar = AllAimObjectType.SecondarySurveillanceRadar,
		HoldingAssessment = AllAimObjectType.HoldingAssessment,
		StandardLevelTable = AllAimObjectType.StandardLevelTable,
		StandardLevelSector = AllAimObjectType.StandardLevelSector,
		StandardLevelColumn = AllAimObjectType.StandardLevelColumn,
		RadioFrequencyArea = AllAimObjectType.RadioFrequencyArea,
		SpecialDate = AllAimObjectType.SpecialDate,
		RadioCommunicationChannel = AllAimObjectType.RadioCommunicationChannel,
		PilotControlledLighting = AllAimObjectType.PilotControlledLighting,
		InformationService = AllAimObjectType.InformationService,
		GroundTrafficControlService = AllAimObjectType.GroundTrafficControlService,
		AirTrafficControlService = AllAimObjectType.AirTrafficControlService,
		AirTrafficManagementService = AllAimObjectType.AirTrafficManagementService,
		SearchRescueService = AllAimObjectType.SearchRescueService,
		PassengerService = AllAimObjectType.PassengerService,
		AircraftGroundService = AllAimObjectType.AircraftGroundService,
		FireFightingService = AllAimObjectType.FireFightingService,
		AirportClearanceService = AllAimObjectType.AirportClearanceService,
		AirportSuppliesService = AllAimObjectType.AirportSuppliesService,
		AngleIndication = AllAimObjectType.AngleIndication,
		DistanceIndication = AllAimObjectType.DistanceIndication,
		Azimuth = AllAimObjectType.Azimuth,
		CheckpointINS = AllAimObjectType.CheckpointINS,
		CheckpointVOR = AllAimObjectType.CheckpointVOR,
		DME = AllAimObjectType.DME,
		Elevation = AllAimObjectType.Elevation,
		Glidepath = AllAimObjectType.Glidepath,
		Localizer = AllAimObjectType.Localizer,
		MarkerBeacon = AllAimObjectType.MarkerBeacon,
		Navaid = AllAimObjectType.Navaid,
		SDF = AllAimObjectType.SDF,
		NDB = AllAimObjectType.NDB,
		SpecialNavigationStation = AllAimObjectType.SpecialNavigationStation,
		VOR = AllAimObjectType.VOR,
		TACAN = AllAimObjectType.TACAN,
		SpecialNavigationSystem = AllAimObjectType.SpecialNavigationSystem,
		DirectionFinder = AllAimObjectType.DirectionFinder,
		DesignatedPoint = AllAimObjectType.DesignatedPoint,
		SignificantPointInAirspace = AllAimObjectType.SignificantPointInAirspace,
		AeronauticalGroundLight = AllAimObjectType.AeronauticalGroundLight,
		OrganisationAuthority = AllAimObjectType.OrganisationAuthority,
		Unit = AllAimObjectType.Unit,
		ObstacleArea = AllAimObjectType.ObstacleArea,
		VerticalStructure = AllAimObjectType.VerticalStructure,
		CirclingArea = AllAimObjectType.CirclingArea,
		TerminalArrivalArea = AllAimObjectType.TerminalArrivalArea,
		InstrumentApproachProcedure = AllAimObjectType.InstrumentApproachProcedure,
		StandardInstrumentDeparture = AllAimObjectType.StandardInstrumentDeparture,
		NavigationArea = AllAimObjectType.NavigationArea,
		StandardInstrumentArrival = AllAimObjectType.StandardInstrumentArrival,
		NavigationAreaRestriction = AllAimObjectType.NavigationAreaRestriction,
		ArrivalFeederLeg = AllAimObjectType.ArrivalFeederLeg,
		ArrivalLeg = AllAimObjectType.ArrivalLeg,
		DepartureLeg = AllAimObjectType.DepartureLeg,
		FinalLeg = AllAimObjectType.FinalLeg,
		InitialLeg = AllAimObjectType.InitialLeg,
		IntermediateLeg = AllAimObjectType.IntermediateLeg,
		MissedApproachLeg = AllAimObjectType.MissedApproachLeg,
		ProcedureDME = AllAimObjectType.ProcedureDME,
		SafeAltitudeArea = AllAimObjectType.SafeAltitudeArea,
		HoldingPattern = AllAimObjectType.HoldingPattern,
		UnplannedHolding = AllAimObjectType.UnplannedHolding,
		AirspaceBorderCrossing = AllAimObjectType.AirspaceBorderCrossing,
		FlightRestriction = AllAimObjectType.FlightRestriction,
		RouteSegment = AllAimObjectType.RouteSegment,
		RouteDME = AllAimObjectType.RouteDME,
		Route = AllAimObjectType.Route,
		ChangeOverPoint = AllAimObjectType.ChangeOverPoint,
		AerialRefuelling = AllAimObjectType.AerialRefuelling,
		RulesProcedures = AllAimObjectType.RulesProcedures
	}
	
	public enum AbstractType
	{
		SurfaceContamination = AllAimObjectType.SurfaceContamination,
		UsageCondition = AllAimObjectType.UsageCondition,
		PropertiesWithSchedule = AllAimObjectType.PropertiesWithSchedule,
		SegmentPoint = AllAimObjectType.SegmentPoint,
		DirectFlight = AllAimObjectType.DirectFlight,
		MDIdentification = AllAimObjectType.MDIdentification,
		GroundLightSystem = AllAimObjectType.GroundLightSystem,
		Marking = AllAimObjectType.Marking,
		AirportHeliportProtectionArea = AllAimObjectType.AirportHeliportProtectionArea,
		RadarEquipment = AllAimObjectType.RadarEquipment,
		SurveillanceRadar = AllAimObjectType.SurveillanceRadar,
		Service = AllAimObjectType.Service,
		TrafficSeparationService = AllAimObjectType.TrafficSeparationService,
		AirportGroundService = AllAimObjectType.AirportGroundService,
		NavaidEquipment = AllAimObjectType.NavaidEquipment,
		NavigationSystemCheckpoint = AllAimObjectType.NavigationSystemCheckpoint,
		Procedure = AllAimObjectType.Procedure,
		SegmentLeg = AllAimObjectType.SegmentLeg,
		ApproachLeg = AllAimObjectType.ApproachLeg,

        #region ISO METADATA ABSTRACT TYPES
        
	    BtAbstractObject = AllAimObjectType.BtAbstractObject,
	    BtAbstractTimePrimitive = AllAimObjectType.BtAbstractTimePrimitive,
	    MdConstraints = AllAimObjectType.MdConstraints,
	    MdAbstractIdentification = AllAimObjectType.MdAbstractIdentification,
	    DqAbstractResult = AllAimObjectType.DqAbstractResult,
	    DqAbstractElement = AllAimObjectType.DqAbstractElement

        #endregion
    }
	
	public enum EnumType
	{
		CIRoleCode = AllAimObjectType.CIRoleCode,
		CIDateTypeCode = AllAimObjectType.CIDateTypeCode,
		DQEvaluationMethodTypeCode = AllAimObjectType.DQEvaluationMethodTypeCode,
		MDProgressCode = AllAimObjectType.MDProgressCode,
		UomFL = AllAimObjectType.UomFL,
		UomDistance = AllAimObjectType.UomDistance,
		UomDistanceVertical = AllAimObjectType.UomDistanceVertical,
		UomDuration = AllAimObjectType.UomDuration,
		UomFrequency = AllAimObjectType.UomFrequency,
		UomPressure = AllAimObjectType.UomPressure,
		UomSpeed = AllAimObjectType.UomSpeed,
		UomTemperature = AllAimObjectType.UomTemperature,
		UomWeight = AllAimObjectType.UomWeight,
		UomDepth = AllAimObjectType.UomDepth,
		UomLightIntensity = AllAimObjectType.UomLightIntensity,
		CodeAircraftEngineNumber = AllAimObjectType.CodeAircraftEngineNumber,
		CodeAirspaceActivity = AllAimObjectType.CodeAirspaceActivity,
		CodeAircraftCategory = AllAimObjectType.CodeAircraftCategory,
		CodeFireFighting = AllAimObjectType.CodeFireFighting,
		CodeFuel = AllAimObjectType.CodeFuel,
		CodeOil = AllAimObjectType.CodeOil,
		CodeDMEChannel = AllAimObjectType.CodeDMEChannel,
		CodeMLSChannel = AllAimObjectType.CodeMLSChannel,
		CodeTACANChannel = AllAimObjectType.CodeTACANChannel,
		CodeHelicopterPerformance = AllAimObjectType.CodeHelicopterPerformance,
		CodeMarkerBeaconSignal = AllAimObjectType.CodeMarkerBeaconSignal,
		CodeNDBUsage = AllAimObjectType.CodeNDBUsage,
		CodeColour = AllAimObjectType.CodeColour,
		CodeTimeEventCombination = AllAimObjectType.CodeTimeEventCombination,
		CodeComparison = AllAimObjectType.CodeComparison,
		CodeSurfaceComposition = AllAimObjectType.CodeSurfaceComposition,
		CodeSurfaceCondition = AllAimObjectType.CodeSurfaceCondition,
		CodeDay = AllAimObjectType.CodeDay,
		CodeAltitudeUse = AllAimObjectType.CodeAltitudeUse,
		CodeDirection = AllAimObjectType.CodeDirection,
		CodeDirectionReference = AllAimObjectType.CodeDirectionReference,
		CodeDirectionTurn = AllAimObjectType.CodeDirectionTurn,
		CodeVerticalReference = AllAimObjectType.CodeVerticalReference,
		CodeRadioEmission = AllAimObjectType.CodeRadioEmission,
		CodeFlowConditionOperation = AllAimObjectType.CodeFlowConditionOperation,
		CodeFlightStatus = AllAimObjectType.CodeFlightStatus,
		CodeFlight = AllAimObjectType.CodeFlight,
		CodeProcedureFixRole = AllAimObjectType.CodeProcedureFixRole,
		CodeLevelTableDesignator = AllAimObjectType.CodeLevelTableDesignator,
		CodeRouteOrigin = AllAimObjectType.CodeRouteOrigin,
		CodeLightIntensity = AllAimObjectType.CodeLightIntensity,
		CodeAviationStandards = AllAimObjectType.CodeAviationStandards,
		CodeLevel = AllAimObjectType.CodeLevel,
		CodeMilitaryStatus = AllAimObjectType.CodeMilitaryStatus,
		CodeAirspaceAggregation = AllAimObjectType.CodeAirspaceAggregation,
		CodeFlightOrigin = AllAimObjectType.CodeFlightOrigin,
		CodePCNMethod = AllAimObjectType.CodePCNMethod,
		CodePCNTyrePressure = AllAimObjectType.CodePCNTyrePressure,
		CodePCNSubgrade = AllAimObjectType.CodePCNSubgrade,
		CodePCNPavement = AllAimObjectType.CodePCNPavement,
		CodeProcedurePhase = AllAimObjectType.CodeProcedurePhase,
		CodeSurfacePreparation = AllAimObjectType.CodeSurfacePreparation,
		CodeApronSection = AllAimObjectType.CodeApronSection,
		CodePositionInILS = AllAimObjectType.CodePositionInILS,
		CodeSide = AllAimObjectType.CodeSide,
		CodeRunwaySection = AllAimObjectType.CodeRunwaySection,
		CodeTLOFSection = AllAimObjectType.CodeTLOFSection,
		CodeTaxiwaySection = AllAimObjectType.CodeTaxiwaySection,
		CodeFlightPurpose = AllAimObjectType.CodeFlightPurpose,
		CodeLocationQualifier = AllAimObjectType.CodeLocationQualifier,
		CodeATCReporting = AllAimObjectType.CodeATCReporting,
		CodeRouteAvailability = AllAimObjectType.CodeRouteAvailability,
		CodeRVSMPointRole = AllAimObjectType.CodeRVSMPointRole,
		CodeSpecialDate = AllAimObjectType.CodeSpecialDate,
		CodeSpeedReference = AllAimObjectType.CodeSpeedReference,
		CodeTimeEvent = AllAimObjectType.CodeTimeEvent,
		CodeTimeReference = AllAimObjectType.CodeTimeReference,
		CodeAircraft = AllAimObjectType.CodeAircraft,
		CodeAircraftEngine = AllAimObjectType.CodeAircraftEngine,
		CodeAirportHeliport = AllAimObjectType.CodeAirportHeliport,
		CodeAirportHeliportCollocation = AllAimObjectType.CodeAirportHeliportCollocation,
		CodeGroundLighting = AllAimObjectType.CodeGroundLighting,
		CodeApproachLighting = AllAimObjectType.CodeApproachLighting,
		CodeBearing = AllAimObjectType.CodeBearing,
		CodeAirspace = AllAimObjectType.CodeAirspace,
		CodeAuthority = AllAimObjectType.CodeAuthority,
		CodeAirspacePointRole = AllAimObjectType.CodeAirspacePointRole,
		CodeOrganisationHierarchy = AllAimObjectType.CodeOrganisationHierarchy,
		CodeMLSAzimuth = AllAimObjectType.CodeMLSAzimuth,
		CodeCourse = AllAimObjectType.CodeCourse,
		CodeDeclaredDistance = AllAimObjectType.CodeDeclaredDistance,
		CodeDesignatedPoint = AllAimObjectType.CodeDesignatedPoint,
		CodeDME = AllAimObjectType.CodeDME,
		CodeFlightRule = AllAimObjectType.CodeFlightRule,
		CodeGeoBorder = AllAimObjectType.CodeGeoBorder,
		CodeHoldingUsage = AllAimObjectType.CodeHoldingUsage,
		CodeLightSource = AllAimObjectType.CodeLightSource,
		CodeMilitaryOperations = AllAimObjectType.CodeMilitaryOperations,
		CodeRadioFrequencyArea = AllAimObjectType.CodeRadioFrequencyArea,
		CodeNitrogen = AllAimObjectType.CodeNitrogen,
		CodeNorthReference = AllAimObjectType.CodeNorthReference,
		CodeOrganisation = AllAimObjectType.CodeOrganisation,
		CodeOxygen = AllAimObjectType.CodeOxygen,
		CodeSegmentPath = AllAimObjectType.CodeSegmentPath,
		CodeRunwayProtectionArea = AllAimObjectType.CodeRunwayProtectionArea,
		CodeFlightRestriction = AllAimObjectType.CodeFlightRestriction,
		CodeRouteNavigation = AllAimObjectType.CodeRouteNavigation,
		CodeRouteSegmentPath = AllAimObjectType.CodeRouteSegmentPath,
		CodeAircraftGroundService = AllAimObjectType.CodeAircraftGroundService,
		CodeSpecialNavigationStation = AllAimObjectType.CodeSpecialNavigationStation,
		CodeSpecialNavigationSystem = AllAimObjectType.CodeSpecialNavigationSystem,
		CodeAircraftStand = AllAimObjectType.CodeAircraftStand,
		CodeTaxiway = AllAimObjectType.CodeTaxiway,
		CodeUnit = AllAimObjectType.CodeUnit,
		CodeILSBackCourse = AllAimObjectType.CodeILSBackCourse,
		CodeVASIS = AllAimObjectType.CodeVASIS,
		CodeUsageLimitation = AllAimObjectType.CodeUsageLimitation,
		CodeStatusConstruction = AllAimObjectType.CodeStatusConstruction,
		CodeStatusOperations = AllAimObjectType.CodeStatusOperations,
		CodeVerticalStructure = AllAimObjectType.CodeVerticalStructure,
		CodeVerticalStructureMarking = AllAimObjectType.CodeVerticalStructureMarking,
		CodeCardinalDirection = AllAimObjectType.CodeCardinalDirection,
		CodeFreeFlight = AllAimObjectType.CodeFreeFlight,
		CodeNavaidService = AllAimObjectType.CodeNavaidService,
		CodeVerticalDatum = AllAimObjectType.CodeVerticalDatum,
		CodeRouteDesignatorPrefix = AllAimObjectType.CodeRouteDesignatorPrefix,
		CodeRVSM = AllAimObjectType.CodeRVSM,
		CodeRouteDesignatorLetter = AllAimObjectType.CodeRouteDesignatorLetter,
		CodeRouteDesignatorSuffix = AllAimObjectType.CodeRouteDesignatorSuffix,
		CodeStatusAirspace = AllAimObjectType.CodeStatusAirspace,
		CodeRunwayPointRole = AllAimObjectType.CodeRunwayPointRole,
		CodeRunway = AllAimObjectType.CodeRunway,
		CodeMarkingStyle = AllAimObjectType.CodeMarkingStyle,
		CodeFinalGuidance = AllAimObjectType.CodeFinalGuidance,
		CodeMissedApproach = AllAimObjectType.CodeMissedApproach,
		CodeUpperAlpha = AllAimObjectType.CodeUpperAlpha,
		CodeApproachPrefix = AllAimObjectType.CodeApproachPrefix,
		CodeApproach = AllAimObjectType.CodeApproach,
		CodeApproval = AllAimObjectType.CodeApproval,
		CodeDesignStandard = AllAimObjectType.CodeDesignStandard,
		CodeApproachEquipmentAdditional = AllAimObjectType.CodeApproachEquipmentAdditional,
		CodeEquipmentUnavailable = AllAimObjectType.CodeEquipmentUnavailable,
		CodeHoldingUse = AllAimObjectType.CodeHoldingUse,
		CodeProcedureDistance = AllAimObjectType.CodeProcedureDistance,
		CodeMinimaFinalApproachPath = AllAimObjectType.CodeMinimaFinalApproachPath,
		CodeMinimumAltitude = AllAimObjectType.CodeMinimumAltitude,
		CodeMinimumHeight = AllAimObjectType.CodeMinimumHeight,
		CodeProcedureCodingStandard = AllAimObjectType.CodeProcedureCodingStandard,
		CodeSafeAltitude = AllAimObjectType.CodeSafeAltitude,
		CodeObstacleAssessmentSurface = AllAimObjectType.CodeObstacleAssessmentSurface,
		CodeAltitudeAdjustment = AllAimObjectType.CodeAltitudeAdjustment,
		CodeTAA = AllAimObjectType.CodeTAA,
		CodeArcDirection = AllAimObjectType.CodeArcDirection,
		CodeLevelSeries = AllAimObjectType.CodeLevelSeries,
		CodeSegmentTermination = AllAimObjectType.CodeSegmentTermination,
		CodeReferenceRole = AllAimObjectType.CodeReferenceRole,
		CodeTrajectory = AllAimObjectType.CodeTrajectory,
		CodeRunwayMarking = AllAimObjectType.CodeRunwayMarking,
		CodeRVRReading = AllAimObjectType.CodeRVRReading,
		CodeStatusNavaid = AllAimObjectType.CodeStatusNavaid,
		CodeOperationAirportHeliport = AllAimObjectType.CodeOperationAirportHeliport,
		CodeDistanceIndication = AllAimObjectType.CodeDistanceIndication,
		CodeObstacleArea = AllAimObjectType.CodeObstacleArea,
		CodeAirspaceClassification = AllAimObjectType.CodeAirspaceClassification,
		CodeApronElement = AllAimObjectType.CodeApronElement,
		CodeRunwayElement = AllAimObjectType.CodeRunwayElement,
		CodeAuthorityRole = AllAimObjectType.CodeAuthorityRole,
		CodeVOR = AllAimObjectType.CodeVOR,
		CodeApproachLightingICAO = AllAimObjectType.CodeApproachLightingICAO,
		CodeLightingJAR = AllAimObjectType.CodeLightingJAR,
		CodeWorkArea = AllAimObjectType.CodeWorkArea,
		CodeVerticalStructureMaterial = AllAimObjectType.CodeVerticalStructureMaterial,
		CodeGuidanceLine = AllAimObjectType.CodeGuidanceLine,
		CodeAirportWarning = AllAimObjectType.CodeAirportWarning,
		CodeProtectAreaSection = AllAimObjectType.CodeProtectAreaSection,
		CodeRoute = AllAimObjectType.CodeRoute,
		CodeAirspacePointPosition = AllAimObjectType.CodeAirspacePointPosition,
		CodeContamination = AllAimObjectType.CodeContamination,
		CodeFrictionDevice = AllAimObjectType.CodeFrictionDevice,
		CodeFrictionEstimate = AllAimObjectType.CodeFrictionEstimate,
		CodeHeightReference = AllAimObjectType.CodeHeightReference,
		CodeAerialRefuellingPoint = AllAimObjectType.CodeAerialRefuellingPoint,
		CodeAerialRefuelling = AllAimObjectType.CodeAerialRefuelling,
		CodeLoadingBridge = AllAimObjectType.CodeLoadingBridge,
		CodeApproachGuidance = AllAimObjectType.CodeApproachGuidance,
		CodeAircraftWingspanClass = AllAimObjectType.CodeAircraftWingspanClass,
		CodeArrestingGearEngageDevice = AllAimObjectType.CodeArrestingGearEngageDevice,
		CodeObstructionIdSurfaceZone = AllAimObjectType.CodeObstructionIdSurfaceZone,
		CodeBuoy = AllAimObjectType.CodeBuoy,
		CodeRoad = AllAimObjectType.CodeRoad,
		CodeAerialRefuellingPrefix = AllAimObjectType.CodeAerialRefuellingPrefix,
		CodeMilitaryTraining = AllAimObjectType.CodeMilitaryTraining,
		CodeFacilityRanking = AllAimObjectType.CodeFacilityRanking,
		CodeMilitaryRoutePoint = AllAimObjectType.CodeMilitaryRoutePoint,
		CodeArrestingGearEnergyAbsorb = AllAimObjectType.CodeArrestingGearEnergyAbsorb,
		CodeEmissionBand = AllAimObjectType.CodeEmissionBand,
		CodeMeteoConditions = AllAimObjectType.CodeMeteoConditions,
		CodeValueInterpretation = AllAimObjectType.CodeValueInterpretation,
		CodeNavigationArea = AllAimObjectType.CodeNavigationArea,
		CodeProcedureAvailability = AllAimObjectType.CodeProcedureAvailability,
		CodePilotControlledLighting = AllAimObjectType.CodePilotControlledLighting,
		CodeIntensityStandBy = AllAimObjectType.CodeIntensityStandBy,
		CodeTelecomNetwork = AllAimObjectType.CodeTelecomNetwork,
		CodeFlightDestination = AllAimObjectType.CodeFlightDestination,
		CodeServiceInformation = AllAimObjectType.CodeServiceInformation,
		CodeServiceATFM = AllAimObjectType.CodeServiceATFM,
		CodeServiceATC = AllAimObjectType.CodeServiceATC,
		CodeServiceSAR = AllAimObjectType.CodeServiceSAR,
		CodeCommunicationChannel = AllAimObjectType.CodeCommunicationChannel,
		CodePassengerService = AllAimObjectType.CodePassengerService,
		CodeServiceGroundControl = AllAimObjectType.CodeServiceGroundControl,
		CodeStatusService = AllAimObjectType.CodeStatusService,
		CodeCommunicationMode = AllAimObjectType.CodeCommunicationMode,
		CodeCommunicationDirection = AllAimObjectType.CodeCommunicationDirection,
		CodeCheckpointCategory = AllAimObjectType.CodeCheckpointCategory,
		CodeLightHoldingPosition = AllAimObjectType.CodeLightHoldingPosition,
		CodeNavigationAreaRestriction = AllAimObjectType.CodeNavigationAreaRestriction,
		CodeSystemActivation = AllAimObjectType.CodeSystemActivation,
		CodeWakeTurbulence = AllAimObjectType.CodeWakeTurbulence,
		CodePAR = AllAimObjectType.CodePAR,
		CodePrimaryRadar = AllAimObjectType.CodePrimaryRadar,
		CodeRadarService = AllAimObjectType.CodeRadarService,
		CodeReflector = AllAimObjectType.CodeReflector,
		CodeStandbyPower = AllAimObjectType.CodeStandbyPower,
		CodeTransponder = AllAimObjectType.CodeTransponder,
		CodeAirspaceDependency = AllAimObjectType.CodeAirspaceDependency,
		CodeUnitDependency = AllAimObjectType.CodeUnitDependency,
		CodeVisualDockingGuidance = AllAimObjectType.CodeVisualDockingGuidance,
		CodeMarkingCondition = AllAimObjectType.CodeMarkingCondition,
		CodeNavaidPurpose = AllAimObjectType.CodeNavaidPurpose,
		CodeRuleProcedure = AllAimObjectType.CodeRuleProcedure,
		CodeRuleProcedureTitle = AllAimObjectType.CodeRuleProcedureTitle,
		CodeGradeSeparation = AllAimObjectType.CodeGradeSeparation,
		CodeTaxiwayElement = AllAimObjectType.CodeTaxiwayElement,
		CodeRadioSignal = AllAimObjectType.CodeRadioSignal,
		CodeSignalPerformanceILS = AllAimObjectType.CodeSignalPerformanceILS,
		CodeCourseQualityILS = AllAimObjectType.CodeCourseQualityILS,
		CodeIntegrityLevelILS = AllAimObjectType.CodeIntegrityLevelILS,
		CodeHoldingCategory = AllAimObjectType.CodeHoldingCategory,
		CodeNotePurpose = AllAimObjectType.CodeNotePurpose,
		CodeNavigationEquipment = AllAimObjectType.CodeNavigationEquipment,
		CodeNavigationSpecification = AllAimObjectType.CodeNavigationSpecification,
		CodeEquipmentAntiCollision = AllAimObjectType.CodeEquipmentAntiCollision,
		CodeLogicalOperator = AllAimObjectType.CodeLogicalOperator,
		CodeStatusAirport = AllAimObjectType.CodeStatusAirport,
		CodeOperationManoeuvringArea = AllAimObjectType.CodeOperationManoeuvringArea,
		CodeRelativePosition = AllAimObjectType.CodeRelativePosition,
		TimeSliceInterpretationType = AllAimObjectType.TimeSliceInterpretationType,
		PhoneCodeType = AllAimObjectType.PhoneCodeType,
		LanguageCodeType = AllAimObjectType.LanguageCodeType,
		RestrictionCode = AllAimObjectType.RestrictionCode,
		ClassificationCode = AllAimObjectType.ClassificationCode,
		MeasureClassCode = AllAimObjectType.MeasureClassCode,
		language = AllAimObjectType.Language,
		GroundLightSystemType = AllAimObjectType.GroundLightSystemType,
		MarkingType = AllAimObjectType.MarkingType,
		AirportHeliportProtectionAreaType = AllAimObjectType.AirportHeliportProtectionAreaType,
		RadarEquipmentType = AllAimObjectType.RadarEquipmentType,
		SurveillanceRadarType = AllAimObjectType.SurveillanceRadarType,
		ServiceType = AllAimObjectType.ServiceType,
		TrafficSeparationServiceType = AllAimObjectType.TrafficSeparationServiceType,
		AirportGroundServiceType = AllAimObjectType.AirportGroundServiceType,
		NavaidEquipmentType = AllAimObjectType.NavaidEquipmentType,
		NavigationSystemCheckpointType = AllAimObjectType.NavigationSystemCheckpointType,
		ProcedureType = AllAimObjectType.ProcedureType,
		SegmentLegType = AllAimObjectType.SegmentLegType,
		ApproachLegType = AllAimObjectType.ApproachLegType,

        #region ISO METADATA ENUMS

        MdOnLineFunctionCode = AllAimObjectType.MdOnLineFunctionCode,
	    CiDateTypeCode = AllAimObjectType.CiDateTypeCode,
	    CiRoleCode = AllAimObjectType.CiRoleCode,
	    CiPresentationFormCode = AllAimObjectType.CiPresentationFormCode,
	    MdTimeIndeterminateValueType = AllAimObjectType.MdTimeIndeterminateValueType,
	    DqEvaluationMethodTypeCode = AllAimObjectType.DqEvaluationMethodTypeCode,
	    MdRestrictionCode = AllAimObjectType.MdRestrictionCode,
	    MdClassificationCode = AllAimObjectType.MdClassificationCode,
	    MdProgressCode = AllAimObjectType.MdProgressCode

        #endregion
    }
	
	public enum ArrestingGearExtentChoice
	{
		ElevatedCurve = AllAimObjectType.ElevatedCurve,
		ElevatedSurface = AllAimObjectType.ElevatedSurface,
		ElevatedPoint = AllAimObjectType.ElevatedPoint
	}
	
	public enum GroundLightSystemType
	{
		VisualGlideSlopeIndicator = AllAimObjectType.VisualGlideSlopeIndicator,
		ApronLightSystem = AllAimObjectType.ApronLightSystem,
		TaxiwayLightSystem = AllAimObjectType.TaxiwayLightSystem,
		RunwayDirectionLightSystem = AllAimObjectType.RunwayDirectionLightSystem,
		TouchDownLiftOffLightSystem = AllAimObjectType.TouchDownLiftOffLightSystem,
		GuidanceLineLightSystem = AllAimObjectType.GuidanceLineLightSystem,
		RunwayProtectAreaLightSystem = AllAimObjectType.RunwayProtectAreaLightSystem,
		TaxiHoldingPositionLightSystem = AllAimObjectType.TaxiHoldingPositionLightSystem,
		ApproachLightingSystem = AllAimObjectType.ApproachLightingSystem
	}
	
	public enum MarkingType
	{
		TaxiwayMarking = AllAimObjectType.TaxiwayMarking,
		ApronMarking = AllAimObjectType.ApronMarking,
		AirportProtectionAreaMarking = AllAimObjectType.AirportProtectionAreaMarking,
		TouchDownLiftOffMarking = AllAimObjectType.TouchDownLiftOffMarking,
		RunwayMarking = AllAimObjectType.RunwayMarking,
		GuidanceLineMarking = AllAimObjectType.GuidanceLineMarking,
		DeicingAreaMarking = AllAimObjectType.DeicingAreaMarking,
		TaxiHoldingPositionMarking = AllAimObjectType.TaxiHoldingPositionMarking,
		StandMarking = AllAimObjectType.StandMarking
	}
	
	public enum MarkingExtentChoice
	{
		ElevatedSurface = AllAimObjectType.ElevatedSurface,
		ElevatedCurve = AllAimObjectType.ElevatedCurve,
		ElevatedPoint = AllAimObjectType.ElevatedPoint
	}
	
	public enum SurfaceContaminationType
	{
		RunwayContamination = AllAimObjectType.RunwayContamination,
		TaxiwayContamination = AllAimObjectType.TaxiwayContamination,
		RunwaySectionContamination = AllAimObjectType.RunwaySectionContamination,
		TouchDownLiftOffContamination = AllAimObjectType.TouchDownLiftOffContamination,
		ApronContamination = AllAimObjectType.ApronContamination,
		AircraftStandContamination = AllAimObjectType.AircraftStandContamination,
		AirportHeliportContamination = AllAimObjectType.AirportHeliportContamination
	}
	
	public enum UsageConditionType
	{
		ManoeuvringAreaUsage = AllAimObjectType.ManoeuvringAreaUsage,
		ApronAreaUsage = AllAimObjectType.ApronAreaUsage,
		AirportHeliportUsage = AllAimObjectType.AirportHeliportUsage
	}
	
	public enum AirportHeliportProtectionAreaType
	{
		RunwayProtectArea = AllAimObjectType.RunwayProtectArea,
		TouchDownLiftOffSafeArea = AllAimObjectType.TouchDownLiftOffSafeArea
	}
	
	public enum RadarEquipmentType
	{
		PrecisionApproachRadar = AllAimObjectType.PrecisionApproachRadar,
		PrimarySurveillanceRadar = AllAimObjectType.PrimarySurveillanceRadar,
		SecondarySurveillanceRadar = AllAimObjectType.SecondarySurveillanceRadar
	}
	
	public enum SurveillanceRadarType
	{
		PrimarySurveillanceRadar = AllAimObjectType.PrimarySurveillanceRadar,
		SecondarySurveillanceRadar = AllAimObjectType.SecondarySurveillanceRadar
	}
	
	public enum EquipmentChoiceChoice
	{
		AbstractNavaidEquipmentRef = AllAimObjectType.AbstractNavaidEquipmentRef,
		RadioCommunicationChannel = AllAimObjectType.RadioCommunicationChannel,
		SpecialNavigationStation = AllAimObjectType.SpecialNavigationStation,
		PrecisionApproachRadar = AllAimObjectType.PrecisionApproachRadar,
		SecondarySurveillanceRadar = AllAimObjectType.SecondarySurveillanceRadar
	}
	
	public enum PropertiesWithScheduleType
	{
		RunwayDeclaredDistanceValue = AllAimObjectType.RunwayDeclaredDistanceValue,
		ManoeuvringAreaAvailability = AllAimObjectType.ManoeuvringAreaAvailability,
		ApronAreaAvailability = AllAimObjectType.ApronAreaAvailability,
		GroundLightingAvailability = AllAimObjectType.GroundLightingAvailability,
		AirportHeliportResponsibilityOrganisation = AllAimObjectType.AirportHeliportResponsibilityOrganisation,
		AltimeterSourceStatus = AllAimObjectType.AltimeterSourceStatus,
		WorkareaActivity = AllAimObjectType.WorkareaActivity,
		ConditionCombination = AllAimObjectType.ConditionCombination,
		AirportHeliportAvailability = AllAimObjectType.AirportHeliportAvailability,
		AirspaceActivation = AllAimObjectType.AirspaceActivation,
		AirspaceLayerClass = AllAimObjectType.AirspaceLayerClass,
		OnlineContact = AllAimObjectType.OnlineContact,
		PostalAddress = AllAimObjectType.PostalAddress,
		TelephoneContact = AllAimObjectType.TelephoneContact,
		LightElementStatus = AllAimObjectType.LightElementStatus,
		ServiceOperationalStatus = AllAimObjectType.ServiceOperationalStatus,
		RadioCommunicationOperationalStatus = AllAimObjectType.RadioCommunicationOperationalStatus,
		NavaidOperationalStatus = AllAimObjectType.NavaidOperationalStatus,
		NavaidEquipmentMonitoring = AllAimObjectType.NavaidEquipmentMonitoring,
		SpecialNavigationStationStatus = AllAimObjectType.SpecialNavigationStationStatus,
		UnitAvailability = AllAimObjectType.UnitAvailability,
		VerticalStructurePart = AllAimObjectType.VerticalStructurePart,
		VerticalStructureLightingStatus = AllAimObjectType.VerticalStructureLightingStatus,
		CirclingRestriction = AllAimObjectType.CirclingRestriction,
		ProcedureAvailability = AllAimObjectType.ProcedureAvailability,
		FlightConditionCombination = AllAimObjectType.FlightConditionCombination,
		RouteAvailability = AllAimObjectType.RouteAvailability
	}
	
	public enum ServiceType
	{
		InformationService = AllAimObjectType.InformationService,
		GroundTrafficControlService = AllAimObjectType.GroundTrafficControlService,
		AirTrafficControlService = AllAimObjectType.AirTrafficControlService,
		AirTrafficManagementService = AllAimObjectType.AirTrafficManagementService,
		SearchRescueService = AllAimObjectType.SearchRescueService,
		PassengerService = AllAimObjectType.PassengerService,
		AircraftGroundService = AllAimObjectType.AircraftGroundService,
		FireFightingService = AllAimObjectType.FireFightingService,
		AirportClearanceService = AllAimObjectType.AirportClearanceService,
		AirportSuppliesService = AllAimObjectType.AirportSuppliesService
	}
	
	public enum TrafficSeparationServiceType
	{
		GroundTrafficControlService = AllAimObjectType.GroundTrafficControlService,
		AirTrafficControlService = AllAimObjectType.AirTrafficControlService
	}
	
	public enum AirportGroundServiceType
	{
		PassengerService = AllAimObjectType.PassengerService,
		AircraftGroundService = AllAimObjectType.AircraftGroundService,
		FireFightingService = AllAimObjectType.FireFightingService,
		AirportClearanceService = AllAimObjectType.AirportClearanceService,
		AirportSuppliesService = AllAimObjectType.AirportSuppliesService
	}
	
	public enum SegmentPointType
	{
		TerminalSegmentPoint = AllAimObjectType.TerminalSegmentPoint,
		EnRouteSegmentPoint = AllAimObjectType.EnRouteSegmentPoint,
		AerialRefuellingPoint = AllAimObjectType.AerialRefuellingPoint
	}
	
	public enum NavaidEquipmentType
	{
		Azimuth = AllAimObjectType.Azimuth,
		DME = AllAimObjectType.DME,
		Elevation = AllAimObjectType.Elevation,
		Glidepath = AllAimObjectType.Glidepath,
		Localizer = AllAimObjectType.Localizer,
		MarkerBeacon = AllAimObjectType.MarkerBeacon,
		SDF = AllAimObjectType.SDF,
		NDB = AllAimObjectType.NDB,
		VOR = AllAimObjectType.VOR,
		TACAN = AllAimObjectType.TACAN,
		DirectionFinder = AllAimObjectType.DirectionFinder
	}
	
	public enum NavigationSystemCheckpointType
	{
		CheckpointINS = AllAimObjectType.CheckpointINS,
		CheckpointVOR = AllAimObjectType.CheckpointVOR
	}
	
	public enum SignificantPointChoice
	{
		DesignatedPoint = AllAimObjectType.DesignatedPoint,
		Navaid = AllAimObjectType.Navaid,
		TouchDownLiftOff = AllAimObjectType.TouchDownLiftOff,
		RunwayCentrelinePoint = AllAimObjectType.RunwayCentrelinePoint,
		AirportHeliport = AllAimObjectType.AirportHeliport,
		AixmPoint = AllAimObjectType.AixmPoint
	}
	
	public enum GuidanceServiceChoice
	{
		Navaid = AllAimObjectType.Navaid,
		SpecialNavigationSystem = AllAimObjectType.SpecialNavigationSystem,
		RadarSystem = AllAimObjectType.RadarSystem
	}
	
	public enum VerticalStructurePartGeometryChoice
	{
		ElevatedPoint = AllAimObjectType.ElevatedPoint,
		ElevatedCurve = AllAimObjectType.ElevatedCurve,
		ElevatedSurface = AllAimObjectType.ElevatedSurface
	}
	
	public enum ObstacleAreaOriginChoice
	{
		AirportHeliport = AllAimObjectType.AirportHeliport,
		RunwayDirection = AllAimObjectType.RunwayDirection,
		OrganisationAuthority = AllAimObjectType.OrganisationAuthority
	}
	
	public enum ProcedureType
	{
		InstrumentApproachProcedure = AllAimObjectType.InstrumentApproachProcedure,
		StandardInstrumentDeparture = AllAimObjectType.StandardInstrumentDeparture,
		StandardInstrumentArrival = AllAimObjectType.StandardInstrumentArrival
	}
	
	public enum SegmentLegType
	{
		ArrivalFeederLeg = AllAimObjectType.ArrivalFeederLeg,
		FinalLeg = AllAimObjectType.FinalLeg,
		InitialLeg = AllAimObjectType.InitialLeg,
		IntermediateLeg = AllAimObjectType.IntermediateLeg,
		MissedApproachLeg = AllAimObjectType.MissedApproachLeg,
		ArrivalLeg = AllAimObjectType.ArrivalLeg,
		DepartureLeg = AllAimObjectType.DepartureLeg
	}
	
	public enum ApproachLegType
	{
		ArrivalFeederLeg = AllAimObjectType.ArrivalFeederLeg,
		FinalLeg = AllAimObjectType.FinalLeg,
		InitialLeg = AllAimObjectType.InitialLeg,
		IntermediateLeg = AllAimObjectType.IntermediateLeg,
		MissedApproachLeg = AllAimObjectType.MissedApproachLeg
	}
	
	public enum HoldingPatternLengthChoice
	{
		HoldingPatternDuration = AllAimObjectType.HoldingPatternDuration,
		HoldingPatternDistance = AllAimObjectType.HoldingPatternDistance,
		SegmentPoint = AllAimObjectType.SegmentPoint
	}
	
	public enum DirectFlightType
	{
		DirectFlightSegment = AllAimObjectType.DirectFlightSegment
	}
	
	public enum FlightConditionElementChoiceChoice
	{
		AirportHeliport = AllAimObjectType.AirportHeliport,
		StandardInstrumentDeparture = AllAimObjectType.StandardInstrumentDeparture,
		RoutePortion = AllAimObjectType.RoutePortion,
		OrganisationAuthority = AllAimObjectType.OrganisationAuthority,
		SignificantPoint = AllAimObjectType.SignificantPoint,
		DirectFlight = AllAimObjectType.DirectFlight,
		AircraftCharacteristic = AllAimObjectType.AircraftCharacteristic,
		AirspaceBorderCrossing = AllAimObjectType.AirspaceBorderCrossing,
		Airspace = AllAimObjectType.Airspace,
		FlightCharacteristic = AllAimObjectType.FlightCharacteristic,
		StandardInstrumentArrival = AllAimObjectType.StandardInstrumentArrival,
		FlightConditionCombination = AllAimObjectType.FlightConditionCombination,
		Meteorology = AllAimObjectType.Meteorology,
		AerialRefuelling = AllAimObjectType.AerialRefuelling
	}
	
	public enum FlightRoutingElementChoiceChoice
	{
		StandardInstrumentArrival = AllAimObjectType.StandardInstrumentArrival,
		Airspace = AllAimObjectType.Airspace,
		SignificantPoint = AllAimObjectType.SignificantPoint,
		DirectFlightSegment = AllAimObjectType.DirectFlightSegment,
		StandardInstrumentDeparture = AllAimObjectType.StandardInstrumentDeparture,
		RoutePortion = AllAimObjectType.RoutePortion,
		AirportHeliport = AllAimObjectType.AirportHeliport,
		AerialRefuelling = AllAimObjectType.AerialRefuelling
	}
	
	public enum MDIdentificationType
	{
		IdentificationMessage = AllAimObjectType.IdentificationMessage,
		IdentificationFeature = AllAimObjectType.IdentificationFeature,
		IdentificationTimesliceFeature = AllAimObjectType.IdentificationTimesliceFeature
	}

    public enum BtAbstractObjectType
    {
        CiTelephone = AllAimObjectType.CiTelephone,
        CiAddress = AllAimObjectType.CiAddress,
        CiOnlineResource = AllAimObjectType.CiOnlineResource,
        CiContact = AllAimObjectType.CiContact,
        CiResponsibleParty = AllAimObjectType.CiResponsibleParty,
        MdIdentifier = AllAimObjectType.MdIdentifier,
        CiSeries = AllAimObjectType.CiSeries,
        CiCitation = AllAimObjectType.CiCitation,
        MdLegalConstraints = AllAimObjectType.MdLegalConstraints,
        MdSecurityConstraints = AllAimObjectType.MdSecurityConstraints,
        MdDataIdentification = AllAimObjectType.MdDataIdentification,
        ExTemporalExtent = AllAimObjectType.ExTemporalExtent,
        ExVerticalExtent = AllAimObjectType.ExVerticalExtent,
        ExExtent = AllAimObjectType.ExExtent,
        DqQuantitativeResult = AllAimObjectType.DqQuantitativeResult,
        DqAbstractElement = AllAimObjectType.DqAbstractElement,
        LiSource = AllAimObjectType.LiSource,
        LiProcessStep = AllAimObjectType.LiProcessStep,
        LiLineage = AllAimObjectType.LiLineage,
        DqDataQuality = AllAimObjectType.DqDataQuality,
        MdMetadata = AllAimObjectType.MdMetadata
    }

    public enum BtAbstractTimePrimitiveType
    {
        BtTimePosition = AllAimObjectType.BtTimePosition,
        BtTimePeriod = AllAimObjectType.BtTimePeriod
    }

    public enum MdConstraintsType
    {
        MdLegalConstraints = AllAimObjectType.MdLegalConstraints,
        MdSecurityConstraints = AllAimObjectType.MdSecurityConstraints
    }

    public enum MdAbstractIdentificationType
    {
        MdDataIdentification = AllAimObjectType.MdDataIdentification
    }

    public enum DqAbstractResultType
    {
        DqQuantitativeResult = AllAimObjectType.DqQuantitativeResult
    }

    public enum DqAbstractElementType
    {
        DqQuantitativeAttributeAccuracy = AllAimObjectType.DqQuantitativeAttributeAccuracy
    }
}
