// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("5.1.18.177")]
[assembly: AssemblyFileVersion("5.1.18.177")]
[assembly: AssemblyCompany("R.I.S.K.")]
[assembly: AssemblyCopyright("Copyright © R.I.S.K., 2014-2018")]


